crime_genres = ['violent', 'property', 'other']
crime_lookup_reverse = { 
    'violent': ['murder', 'robbery', 'aggravated-assault', 'sexual-assault'],
    'property': ['arson', 'theft-from-motor-vehicle', 'auto-theft', 'burglary', 'larceny'],
    'other': ['all-other-crimes', 'drug-alcohol', 'other-crimes-against-persons', 'white-collar-crime', 'public-disorder'] }
crime_lookup = {
    'all-other-crimes': 'other',
    'murder': 'violent',
    'arson': 'property',
    'theft-from-motor-vehicle': 'property',
    'auto-theft': 'property',
    'sexual-assault': 'violent',
    'drug-alcohol': 'other',
    'larceny': 'property',
    'aggravated-assault': 'violent',
    'other-crimes-against-persons': 'other',
    'robbery': 'violent',
    'burglary': 'property',
    'white-collar-crime': 'other',
    'public-disorder': 'other'
}
neighborhood_lookup = {
    'athmar-park': {'full': 'Athmar Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'auraria': {'full': 'Auraria', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'baker': {'full': 'Baker', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'barnum': {'full': 'Barnum', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'barnum-west': {'full': 'Barnum West', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'bear-valley': {'full': 'Bear Valley', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'belcaro': {'full': 'Belcaro', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'berkeley': {'full': 'Berkeley', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'capitol-hill': {'full': 'Capitol Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cbd': {'full': 'CBD', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'chaffee-park': {'full': 'Chaffee Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cheesman-park': {'full': 'Cheesman Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cherry-creek': {'full': 'Cherry Creek', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'city-park': {'full': 'City Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'city-park-west': {'full': 'City Park West', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'civic-center': {'full': 'Civic Center', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'clayton': {'full': 'Clayton', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cole': {'full': 'Cole', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'college-view-south-platte': {'full': 'College View South Platte', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'congress-park': {'full': 'Congress Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cory-merrill': {'full': 'Cory Merrill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'dia': {'full': 'DIA', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'east-colfax': {'full': 'East Colfax', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'elyria-swansea': {'full': 'Elyria Swansea', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'five-points': {'full': 'Five Points', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'gateway-green-valley-ranch': {'full': 'Gateway Green Valley Ranch', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'globeville': {'full': 'Globeville', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'goldsmith': {'full': 'Goldsmith', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'hale': {'full': 'Hale', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'hampden': {'full': 'Hampden', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'hampden-south': {'full': 'Hampden South', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'harvey-park': {'full': 'Harvey Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'harvey-park-south': {'full': 'Harvey Park South', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'highland': {'full': 'Highland', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'hilltop': {'full': 'Hilltop', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'indian-creek': {'full': 'Indian Creek', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'jefferson-park': {'full': 'Jefferson Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'kennedy': {'full': 'Kennedy', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'lincoln-park': {'full': 'Lincoln Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'lowry-field': {'full': 'Lowry Field', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'mar-lee': {'full': 'Mar Lee', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'marston': {'full': 'Marston', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'montbello': {'full': 'Montbello', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'montclair': {'full': 'Montclair', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'north-capitol-hill': {'full': 'North Capitol Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'northeast-park-hill': {'full': 'Northeast Park Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'north-park-hill': {'full': 'North Park Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'overland': {'full': 'Overland', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'platt-park': {'full': 'Platt Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'regis': {'full': 'Regis', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'ruby-hill': {'full': 'Ruby Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'skyland': {'full': 'Skyland', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'sloan-lake': {'full': 'Sloan Lake', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'southmoor-park': {'full': 'Southmoor Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'south-park-hill': {'full': 'South Park Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'speer': {'full': 'Speer', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'stapleton': {'full': 'Stapleton', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'sunnyside': {'full': 'Sunnyside', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'sun-valley': {'full': 'Sun Valley', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'union-station': {'full': 'Union Station', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'university': {'full': 'University', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'university-hills': {'full': 'University Hills', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'university-park': {'full': 'University Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'valverde': {'full': 'Valverde', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'villa-park': {'full': 'Villa Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'virginia-village': {'full': 'Virginia Village', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'washington-park-west': {'full': 'Washington Park West', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'washington-virginia-vale': {'full': 'Washington Virginia Vale', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'west-colfax': {'full': 'West Colfax', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'west-highland': {'full': 'West Highland', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'westwood': {'full': 'Westwood', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'whittier': {'full': 'Whittier', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'windsor': {'full': 'Windsor', 'nearest_neighbors': {}, 'location': {}, 'population': 0}
}
# Human-readable crime names.

crime_name_lookup = {
    'sovereign-treason-viol': {'severity': 0, 'genre': 'other', 'long-name': 'Treason'},
    'immigration-violations': {'severity': 0, 'genre': 'other', 'long-name': 'Immigration violation'},
    'homicide-family': {'severity': 0, 'genre': 'other', 'long-name': 'Homicide by a family member'},
    'hom-willful-kill-non-family-gu': {'severity': 0, 'genre': 'other', 'long-name': 'Homicide by a stranger w/gun'},
    'hom-willful-kill-nonfam-wp': {'severity': 0, 'genre': 'other', 'long-name': 'Homicide by a stranger w/weapon'},
    'homicide-police-by-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Homicide of a Police Officer w/gun'},
    'homicide-police-weapon': {'severity': 0, 'genre': 'other', 'long-name': 'Homicide of a Police Officer w/weapon'},
    'homicide-negligent': {'severity': 0, 'genre': 'other', 'long-name': 'Homicide by negligence'},
    'hom-wilful-kill-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Homicide by gun'},
    'homicide-other': {'severity': 0, 'genre': 'other', 'long-name': 'Homicide by other means'},
    'kidnap-minor-to-sex-aslt': {'severity': 0, 'genre': 'other', 'long-name': 'Kidnap minor to sexually assault'},
    'kidnap-adult-to-sex-aslt': {'severity': 0, 'genre': 'other', 'long-name': 'Kidnap adult to sexually assault'},
    'kidnap-juvenile-victim': {'severity': 0, 'genre': 'other', 'long-name': 'Kidnap a minor'},
    'kidnap-adult-victim': {'severity': 0, 'genre': 'other', 'long-name': 'Kidnap an adult'},
    'kidnap-dv': {'severity': 0, 'genre': 'other', 'long-name': 'Domestic violence kidnapping'},
    'kidnap-abduct-no-ransom-aslt': {'severity': 0, 'genre': 'other', 'long-name': 'Abduction without ransom or assault'},
    'kidnap-hijack-aircraft': {'severity': 0, 'genre': 'other', 'long-name': 'Hijack an aircraft'},
    'kidnap-parental': {'severity': 0, 'genre': 'other', 'long-name': 'Kidnapping by parent'},
    'kidnap-minor-nonparental': {'severity': 0, 'genre': 'other', 'long-name': 'Kidnapping of a minor by non-parent'},
    'false-imprisonment': {'severity': 0, 'genre': 'other', 'long-name': 'False Imprisonment'},
    'sex-aslt-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Rape, perpetrator had a gun'},
    'sex-aslt-rape': {'severity': 0, 'genre': 'other', 'long-name': 'Rape'},
    'sex-aslt-rape-pot': {'severity': 0, 'genre': 'other', 'long-name': 'Rape by a person in a position of trust'},
    'sex-aslt-strong-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Rape using the threat of violence'},
    'sex-aslt-non-rape': {'severity': 0, 'genre': 'other', 'long-name': 'Unlawful sexual contact'},
    'sex-aslt-non-rape-pot': {'severity': 0, 'genre': 'other', 'long-name': 'Unlawful sexual contact'},
    'sex-asslt-sodomy-boy-strng-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Sodomy of a male juvenile using bodily force'},
    'sex-asslt-sodomy-man-strng-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Sodomy of an adult male using bodily force'},
    'sex-asslt-sodomy-girl-strg-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Sodomy of a female juvenile using bodily force'},
    'sex-asslt-sodomy-woman-str-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Sodomy of an adult female using bodily force'},
    'sex-aslt-statutory-rape': {'severity': 0, 'genre': 'other', 'long-name': 'Statutory rape'},
    'sex-aslt-statutory-rape-pot': {'severity': 0, 'genre': 'other', 'long-name': 'Statutory rape by a person in a position of trust'},
    'sex-aslt-w-object': {'severity': 0, 'genre': 'other', 'long-name': 'Sexual assault with an object'},
    'sex-aslt-w-object-pot': {'severity': 0, 'genre': 'other', 'long-name': 'Sexual assault w/object by a person in a position of trust'},
    'robbery-business-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a business using a gun'},
    'robbery-business': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a business using a weapon'},
    'robbery-busn-strong-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a business using bodily force'},
    'robbery-street-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a person in the open using a gun'},
    'robbery-street': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a person in the open'},
    'robbery-street-strong-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a person in the open using bodily force'},
    'robbery-residence-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a person in a residence using a gun'},
    'robbery-residence': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a person in a residence'},
    'robbery-resd-strong-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a person in a residence using bodily force'},
    'robbery-purse-snatch-w-force': {'severity': 0, 'genre': 'other', 'long-name': 'Forcible Purse Snatching'},
    'robbery-bank': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery of a bank'},
    'robbery-car-jacking': {'severity': 0, 'genre': 'other', 'long-name': 'Carjacking - armed'},
    'robbery-other': {'severity': 0, 'genre': 'other', 'long-name': 'Robbery - remarks'},
    'aslt-agg-family-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury by a family member using a gun'},
    'aslt-agg-family-weapon': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury by a family member using a weapon'},
    'agg-aslt-strong-arm-dv': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury using bodily force - domestic violence'},
    'aslt-agg-non-family-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury by a stranger using a gun'},
    'aslt-agg-non-family-weapon': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury by a stranger using a weapon'},
    'agg-aslt-strong-arm-nonfam': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury by a stranger using bodily force'},
    'aslt-agg-police-gun': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury of a police officer using a gun'},
    'agg-aslt-police-weapon': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury of a police officer using a weapon'},
    'agg-aslt-police-ofc-stng-arm': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury of a police officer using bodily force'},
    'assault-simple': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing minor bodily injury'},
    'assault-state': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing minor bodily injury'},
    'assault-dv': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing minor bodily injury - domestic violence'},
    'assault-police-simple': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing minor bodily injury to a police officer'},
    'agg-aslt-gun-other': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury using a gun'},
    'weapon-fire-into-occ-veh': {'severity': 0, 'genre': 'other', 'long-name': 'Weapon fired into an occupied vehicle'},
    'weapon-fire-into-occ-bldg': {'severity': 0, 'genre': 'other', 'long-name': 'Weapon fired into an occupied building'},
    'aggravated-assault': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury'},
    'aggravated-assault-dv': {'severity': 0, 'genre': 'other', 'long-name': 'Assault causing serious bodily injury - domestic violence'},
    'menacing-felony-w-weap': {'severity': 0, 'genre': 'other', 'long-name': 'Threatening to imminently injure with a weapon'},
    'weapon-flourishing': {'severity': 0, 'genre': 'other', 'long-name': 'Flourishing a weapon at another person'},
    'threats-to-injure': {'severity': 0, 'genre': 'other', 'long-name': 'Threatening to injure'},
    'harassment-stalking-dv': {'severity': 0, 'genre': 'other', 'long-name': 'Harassment by stalking - domestic violence'},
    'threats-city': {'severity': 0, 'genre': 'other', 'long-name': 'Threatening to injure'},
    'arson-business': {'severity': 0, 'genre': 'other', 'long-name': 'Arson of a business'},
    'arson-residence': {'severity': 0, 'genre': 'other', 'long-name': 'Arson of a residence'},
    'arson-other': {'severity': 0, 'genre': 'other', 'long-name': 'Arson'},
    'arson-public-building': {'severity': 0, 'genre': 'other', 'long-name': 'Arson to a public building'},
    'arson-vehicle': {'severity': 0, 'genre': 'other', 'long-name': 'Arson of a vehicle'},
    'extort-threat-inj-person': {'severity': 0, 'genre': 'other', 'long-name': 'Extort-threaten to injure a person'},
    'extortion': {'severity': 0, 'genre': 'other', 'long-name': 'Extortion - other'},
    'burglary-safe': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary of a safe'},
    'burglary-residence-by-force': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary of a residence with forced entry'},
    'burg-auto-theft-resd-w-force': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary and auto theft at a residence with forced entry'},
    'burglary-business-by-force': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary of a business with forced entry'},
    'burg-auto-theft-busn-w-force': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary and auto theft at a business with forced entry'},
    'burglary-residence-no-force': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary of a residence without forced entry'},
    'burg-auto-theft-resd-no-force': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary and auto theft at a residence without forced entry'},
    'burglary-business-no-force': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary of a business without forced entry'},
    'burg-auto-theft-busn-no-force': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary and auto theft at a business without forced entry'},
    'burglary-poss-of-tools': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of burglary tools'},
    'burglary-other': {'severity': 0, 'genre': 'other', 'long-name': 'Burglary - other'},
    'theft-pick-pocket': {'severity': 0, 'genre': 'other', 'long-name': 'Pocketpicking'},
    'theft-purse-snatch-no-force': {'severity': 0, 'genre': 'other', 'long-name': 'Purse snatching without force'},
    'theft-shoplift': {'severity': 0, 'genre': 'other', 'long-name': 'Shoplifting'},
    'theft-parts-from-vehicle': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of parts from a vehicle'},
    'theft-items-from-vehicle': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of items from a vehicle'},
    'burglary-vending-machine': {'severity': 0, 'genre': 'other', 'long-name': 'Theft from a vending machine'},
    'theft-from-bldg': {'severity': 0, 'genre': 'other', 'long-name': 'Theft from a building'},
    'theft-from-yards': {'severity': 0, 'genre': 'other', 'long-name': 'Theft from a yard'},
    'theft-from-mails': {'severity': 0, 'genre': 'other', 'long-name': 'Theft from a mailbox'},
    'larc-from-bank-type-inst': {'severity': 0, 'genre': 'other', 'long-name': 'Theft from a bank'},
    'theft-other': {'severity': 0, 'genre': 'other', 'long-name': 'Theft - other'},
    'theft-bicycle': {'severity': 0, 'genre': 'other', 'long-name': 'Bicycle theft'},
    'theft-gas-drive-off': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of fuel by driving off without paying'},
    'theft-of-cable-services': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of cable services'},
    'theft-stln-veh-const-eqpt': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of construction equipment'},
    'theft-stln-vehicle-trailer': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of a trailer'},
    'theft-vehicle-strip': {'severity': 0, 'genre': 'other', 'long-name': 'Vehicle stolen and stripped'},
    'theft-of-motor-vehicle': {'severity': 0, 'genre': 'other', 'long-name': 'Motor vehicle theft'},
    'theft-motor-veh-joy-ride': {'severity': 0, 'genre': 'other', 'long-name': 'Unauthorized use of a vehicle or joy ride'},
    'forgery-checks': {'severity': 0, 'genre': 'other', 'long-name': 'Forgery of checks'},
    'forgery-counterfeit-of-obj': {'severity': 0, 'genre': 'other', 'long-name': 'Counterfeiting an object'},
    'altering-vin-number': {'severity': 0, 'genre': 'other', 'long-name': 'Altering a vehicle VIN number'},
    'forgery-pass-forged-obj': {'severity': 0, 'genre': 'other', 'long-name': 'Passing forged documents'},
    'forg-pass-counterfeit-obj': {'severity': 0, 'genre': 'other', 'long-name': 'Passing counterfeited objects (tickets, bonds, etc)'},
    'forgery-poss-of-forged-inst': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a forged instrument'},
    'forgery-poss-of-forged-ftd': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a forged financial transaction device (credit & debit cards)'},
    'forg-poss-counterfeit-obj': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of counterfeited objects (tickets, bonds, etc)'},
    'forgery-posses-forge-device': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of counterfeiting device'},
    'forgery-other': {'severity': 0, 'genre': 'other', 'long-name': 'Forgery - other'},
    'drug-forgery-to-obtain': {'severity': 0, 'genre': 'other', 'long-name': 'Forgery to obtain drugs'},
    'theft-confidence-game': {'severity': 0, 'genre': 'other', 'long-name': 'Theft by confidence game'},
    'theft-of-rental-property': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of rental property'},
    'theft-fail-return-rent-veh': {'severity': 0, 'genre': 'other', 'long-name': 'Failure to return rental vehicle'},
    'fraud-identity-theft': {'severity': 0, 'genre': 'other', 'long-name': 'Identity theft'},
    'fraud-criminal-impersonation': {'severity': 0, 'genre': 'other', 'long-name': 'Criminal impersonation'},
    'fraud-gather-id-info-deception': {'severity': 0, 'genre': 'other', 'long-name': 'Gathering personal information by deception'},
    'fraud-possess-id-theft-tools': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of identity theft tools'},
    'impersonation-of-police': {'severity': 0, 'genre': 'other', 'long-name': 'Police impersonation'},
    'theft-unauth-use-of-ftd': {'severity': 0, 'genre': 'other', 'long-name': 'Unauthorized use of a financial transaction device'},
    'fraud-unauthorized-use-of-ftd': {'severity': 0, 'genre': 'other', 'long-name': 'Unauthorized use of a financial transaction device'},
    'fraud-nsf-closed-account': {'severity': 0, 'genre': 'other', 'long-name': 'Fraud by check due to insufficient funds'},
    'fraud-by-telephone': {'severity': 0, 'genre': 'other', 'long-name': 'Fraud by telephone'},
    'fraud-by-wire': {'severity': 0, 'genre': 'other', 'long-name': 'Fraud by wire'},
    'fraud-by-use-of-computer': {'severity': 0, 'genre': 'other', 'long-name': 'Fraud by use of computer'},
    'fraud-other': {'severity': 0, 'genre': 'other', 'long-name': 'Fraud - other'},
    'failure-to-pay-cab-fare': {'severity': 0, 'genre': 'other', 'long-name': 'Failure to pay cab, bus or rail fare'},
    'theft-of-meals': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of meals'},
    'theft-of-services': {'severity': 0, 'genre': 'other', 'long-name': 'Theft of services'},
    'drug-fraud-to-obtain': {'severity': 0, 'genre': 'other', 'long-name': 'Fraud to obtain drugs'},
    'pawn-broker-viol': {'severity': 0, 'genre': 'other', 'long-name': 'Pawn broker violation'},
    'embezzle-bus-property': {'severity': 0, 'genre': 'other', 'long-name': 'Embezzlement of business property'},
    'theft-embezzle': {'severity': 0, 'genre': 'other', 'long-name': 'Embezzlement by an employee'},
    'stolen-property-sale-of': {'severity': 0, 'genre': 'other', 'long-name': 'Sale of stolen property'},
    'stolen-property-buy-sell-rec': {'severity': 0, 'genre': 'other', 'long-name': 'Buy, sell or receive stolen property'},
    'outside-steal-recovered-veh': {'severity': 0, 'genre': 'other', 'long-name': 'Recovered vehicle stolen outside Denver'},
    'stolen-property-possession': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of stolen property'},
    'fraud-possess-financial-device': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a financial device'},
    'damaged-prop-bus': {'severity': 0, 'genre': 'other', 'long-name': 'Damaged business property'},
    'criminal-mischief-private': {'severity': 0, 'genre': 'other', 'long-name': 'Criminal mischief to private property'},
    'criminal-mischief-public': {'severity': 0, 'genre': 'other', 'long-name': 'Criminal mischief to public property'},
    'criminal-mischief-other': {'severity': 0, 'genre': 'other', 'long-name': 'Criminal mischief - other'},
    'criminal-mischief-mtr-veh': {'severity': 0, 'genre': 'other', 'long-name': 'Criminal mischief to a motor vehicle'},
    'criminal-mischief-graffiti': {'severity': 0, 'genre': 'other', 'long-name': 'Criminal mischief - graffiti'},
    'drug-hallucinogen-mfr': {'severity': 0, 'genre': 'other', 'long-name': 'Manufacture of a hallucinogenic drug'},
    'drug-hallucinogen-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Selling a hallucinogenic drug'},
    'drug-hallucinogen-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a hallucinogenic drug'},
    'drug-heroin-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Selling heroin'},
    'drug-heroin-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of heroin'},
    'drug-opium-or-deriv-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Selling opium or an opium derivative'},
    'drug-opium-or-deriv-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of opium or an opium derivative'},
    'drug-cocaine-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Selling cocaine'},
    'drug-cocaine-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of cocaine'},
    'drug-synth-narcotic-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Selling a synthetic narcotic drug'},
    'drug-synth-narcotic-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a synthetic narcotic drug'},
    'drug-poss-paraphernalia': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of drug paraphernalia'},
    'drug-marijuana-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Selling marijuana'},
    'drug-marijuana-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of marijuana'},
    'drug-marijuana-cultivation': {'severity': 0, 'genre': 'other', 'long-name': 'Cultivation of marijuana'},
    'drug-methamphetamine-mfr': {'severity': 0, 'genre': 'other', 'long-name': 'Manufacture of methampetamine'},
    'drug-methampetamine-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Selling methampetamine'},
    'drug-methampetamine-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of methampetamine'},
    'drug-barbiturate-mfr': {'severity': 0, 'genre': 'other', 'long-name': 'Manufacture of a barbiturate'},
    'drug-barbiturate-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Selling a barbiturate'},
    'drug-barbiturate-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a barbiturate'},
    'drug-pcs-other-drug': {'severity': 0, 'genre': 'other', 'long-name': 'Other dangerous drugs - PCS'},
    'drug-make-sell-other-drug': {'severity': 0, 'genre': 'other', 'long-name': 'Manufacture or sell other dangerous drugs'},
    'sex-aslt-fondle-adult-victim': {'severity': 0, 'genre': 'other', 'long-name': 'Fondling of an adult'},
    'indecent-exposure': {'severity': 0, 'genre': 'other', 'long-name': 'Indecent exposure'},
    'sex-off-incest-with-adult': {'severity': 0, 'genre': 'other', 'long-name': 'Incest with an adult'},
    'window-peeping': {'severity': 0, 'genre': 'other', 'long-name': 'Window Peeping'},
    'sex-off-fail-to-register': {'severity': 0, 'genre': 'other', 'long-name': 'Failure to register as a sex offender'},
    'sex-off-registration-viol': {'severity': 0, 'genre': 'other', 'long-name': 'Sex offender registration violation'},
    'indecent-exposure-to-adult': {'severity': 0, 'genre': 'other', 'long-name': 'Indecent exposure to an adult'},
    'sex-off-other': {'severity': 0, 'genre': 'other', 'long-name': 'Sex offense - other'},
    'obscene-material-possess': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of obscene material'},
    'obscene-material-mfr': {'severity': 0, 'genre': 'other', 'long-name': 'Manufacture of obscene material'},
    'other-obscenity-crime': {'severity': 0, 'genre': 'other', 'long-name': 'Other obscenity crime'},
    'bigamy': {'severity': 0, 'genre': 'other', 'long-name': 'Bigamy'},
    'gambling-card-game-operating': {'severity': 0, 'genre': 'other', 'long-name': 'Operating a gambling card game'},
    'gambling-dice-game-operating': {'severity': 0, 'genre': 'other', 'long-name': 'Operating a gambling dice game'},
    'gambling-possess-gamb-device': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a gambling device'},
    'gambling-device': {'severity': 0, 'genre': 'other', 'long-name': 'Running a gambling operation'},
    'gambling-lottery-operating': {'severity': 0, 'genre': 'other', 'long-name': 'Running an illegal lottery'},
    'gambling-sports-tampering': {'severity': 0, 'genre': 'other', 'long-name': 'Tampering with sports'},
    'gambling-betting-wagering': {'severity': 0, 'genre': 'other', 'long-name': 'Gambling - betting or wagering'},
    'gambling-gaming-operation': {'severity': 0, 'genre': 'other', 'long-name': 'Gambling - gaming operation'},
    'gambling-illegal': {'severity': 0, 'genre': 'other', 'long-name': 'Illegal gambling'},
    'prostitution-keep-a-house-of': {'severity': 0, 'genre': 'other', 'long-name': 'Keeping a house of prostitution'},
    'prostitution-procure-for': {'severity': 0, 'genre': 'other', 'long-name': 'Procure for prostitution (trafficking, operating a bordelo)'},
    'prostitution-pimping': {'severity': 0, 'genre': 'other', 'long-name': 'Pimping for prostitution'},
    'prostitution-engaging-in': {'severity': 0, 'genre': 'other', 'long-name': 'Engaging in prostitution'},
    'prostitution': {'severity': 0, 'genre': 'other', 'long-name': 'Prostitution'},
    'prostitution-aiding': {'severity': 0, 'genre': 'other', 'long-name': 'Aiding the act of prostitution'},
    'prostituion-display-for': {'severity': 0, 'genre': 'other', 'long-name': 'Display for prostitution'},
    'liquor-manufacturing': {'severity': 0, 'genre': 'other', 'long-name': 'Manufacture of liquor'},
    'liquor-sell': {'severity': 0, 'genre': 'other', 'long-name': 'Illegal sale of liquor'},
    'liquor-possession': {'severity': 0, 'genre': 'other', 'long-name': 'Illegal possession of liquor'},
    'liquor-misrepresent-age-minor': {'severity': 0, 'genre': 'other', 'long-name': 'Liquor law violation'},
    'liquor-other-viol': {'severity': 0, 'genre': 'other', 'long-name': 'Liquor law violation - other'},
    'public-intoxication': {'severity': 0, 'genre': 'other', 'long-name': 'Public intoxication'},
    'police-resisting-arrest': {'severity': 0, 'genre': 'other', 'long-name': 'Resisting arrest'},
    'police-obstruct-investigation': {'severity': 0, 'genre': 'other', 'long-name': 'Obstruction of a criminal investigation'},
    'police-false-information': {'severity': 0, 'genre': 'other', 'long-name': 'Giving false information to police'},
    'police-making-a-false-rpt': {'severity': 0, 'genre': 'other', 'long-name': 'Making a false report to police'},
    'police-refusing-aid-to': {'severity': 0, 'genre': 'other', 'long-name': 'Refusing to aid an officer'},
    'failure-to-report-abuse': {'severity': 0, 'genre': 'other', 'long-name': 'Failure to report abuse'},
    'police-disobey-lawful-order': {'severity': 0, 'genre': 'other', 'long-name': 'Failure to obey a lawful order by police'},
    'police-interference': {'severity': 0, 'genre': 'other', 'long-name': 'Obstructing police'},
    'escape': {'severity': 0, 'genre': 'other', 'long-name': 'Escape of a prisoner'},
    'escape-aiding': {'severity': 0, 'genre': 'other', 'long-name': 'Aiding the escape of a prisoner'},
    'escape-other': {'severity': 0, 'genre': 'other', 'long-name': 'Escape or flight'},
    'intimidation-of-a-witness': {'severity': 0, 'genre': 'other', 'long-name': 'Intimidation of a witness'},
    'obstruct-jud-court-order-vio': {'severity': 0, 'genre': 'other', 'long-name': 'Obstructing a court order'},
    'parole-violation': {'severity': 0, 'genre': 'other', 'long-name': 'Parole violation'},
    'probation-violation': {'severity': 0, 'genre': 'other', 'long-name': 'Probation violation'},
    'failure-to-appear': {'severity': 0, 'genre': 'other', 'long-name': 'Failure to appear'},
    'violation-of-restraining-order': {'severity': 0, 'genre': 'other', 'long-name': 'Violation of a restraining order'},
    'violation-of-court-order': {'severity': 0, 'genre': 'other', 'long-name': 'Violation of a court order'},
    'violation-of-custody-order': {'severity': 0, 'genre': 'other', 'long-name': 'Violation of a court order'},
    'obstructing-govt-operation': {'severity': 0, 'genre': 'other', 'long-name': 'Obstruction of a government operation'},
    'bribery': {'severity': 0, 'genre': 'other', 'long-name': 'Bribery'},
    'weapon-altering-serial-number': {'severity': 0, 'genre': 'other', 'long-name': 'Altering the serial number'},
    'weapon-carrying-concealed': {'severity': 0, 'genre': 'other', 'long-name': 'Carrying a concealed weapon'},
    'weapon-carrying-prohibited': {'severity': 0, 'genre': 'other', 'long-name': 'Carrying a prohibited weapon'},
    'explosive-incendiary-dev-use': {'severity': 0, 'genre': 'other', 'long-name': 'Using an explosive/incendiary device'},
    'explosives-posses': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of an explosive'},
    'explosive-incendiary-dev-pos': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of an explosive/incendiary device'},
    'weapon-poss-illegal-dangerous': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of an illegal/dangerous weapon'},
    'weapon-by-prev-offender-powpo': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a weapon - POWPO'},
    'weapon-unlawful-discharge-of': {'severity': 0, 'genre': 'other', 'long-name': 'Unlawful discharge of a weapon'},
    'weapon-flourishing': {'severity': 0, 'genre': 'other', 'long-name': 'Flourishing of a weapon'},
    'weapon-unlawful-sale': {'severity': 0, 'genre': 'other', 'long-name': 'Unlawful sale of a weapon'},
    'bomb-threat': {'severity': 0, 'genre': 'other', 'long-name': 'Bomb threat'},
    'weapon-other-viol': {'severity': 0, 'genre': 'other', 'long-name': 'Weapon - other'},
    'riot-incite': {'severity': 0, 'genre': 'other', 'long-name': 'Inciting a riot'},
    'riot': {'severity': 0, 'genre': 'other', 'long-name': 'Engaging in a riot'},
    'police-interference': {'severity': 0, 'genre': 'other', 'long-name': 'Police Interference'},
    'riot-unlawful-assembly': {'severity': 0, 'genre': 'other', 'long-name': 'Unlawful assembly'},
    'harassment': {'severity': 0, 'genre': 'other', 'long-name': 'Harassment'},
    'harassment-dv': {'severity': 0, 'genre': 'other', 'long-name': 'Harassment - DV'},
    'harassment-obscene': {'severity': 0, 'genre': 'other', 'long-name': 'Obscene harassment'},
    'harassment-sexual-in-nature': {'severity': 0, 'genre': 'other', 'long-name': 'Harassment - sexual in nature'},
    'pub-peace-desecrate-symb': {'severity': 0, 'genre': 'other', 'long-name': 'Desecrating the flag'},
    'public-fighting': {'severity': 0, 'genre': 'other', 'long-name': 'Public fighting'},
    'disturbing-the-peace': {'severity': 0, 'genre': 'other', 'long-name': 'Disturbing the peace'},
    'curfew': {'severity': 0, 'genre': 'other', 'long-name': 'Curfew'},
    'loitering': {'severity': 0, 'genre': 'other', 'long-name': 'Loitering'},
    'public-peace-vagrancy': {'severity': 0, 'genre': 'other', 'long-name': 'Vagrancy'},
    'public-peace-other': {'severity': 0, 'genre': 'other', 'long-name': 'Public peace - other'},
    'traf-habitual-offender': {'severity': 0, 'genre': 'other', 'long-name': 'Habitual traffic offender'},
    'traf-vehicular-homicide': {'severity': 0, 'genre': 'other', 'long-name': 'Vehicular homicide'},
    'traf-impound-vehicle': {'severity': 0, 'genre': 'other', 'long-name': 'Impound abandoned vehicle on right-of-way'},
    'traf-vehicular-assault': {'severity': 0, 'genre': 'other', 'long-name': 'Vehicular assault'},
    'traf-other': {'severity': 0, 'genre': 'other', 'long-name': 'Traffic offense - other'},
    'vehicular-eluding': {'severity': 0, 'genre': 'other', 'long-name': 'Vehicular eluding'},
    'vehicular-eluding-no-chase': {'severity': 0, 'genre': 'other', 'long-name': 'Vehicular eluding - no chase'},
    'health-violations': {'severity': 0, 'genre': 'other', 'long-name': 'Health & safety violations'},
    'eavesdropping': {'severity': 0, 'genre': 'other', 'long-name': 'Eavesdropping'},
    'criminal-trespassing': {'severity': 0, 'genre': 'other', 'long-name': 'Criminal trespassing'},
    'wiretapping': {'severity': 0, 'genre': 'other', 'long-name': 'Wiretapping'},
    'contraband-possession': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of contraband'},
    'contraband-into-prison': {'severity': 0, 'genre': 'other', 'long-name': 'Smuggle contraband to prisoner'},
    'election-law-violation': {'severity': 0, 'genre': 'other', 'long-name': 'Election laws violation'},
    'money-laundering': {'severity': 0, 'genre': 'other', 'long-name': 'Money laundering'},
    'tax-violations': {'severity': 0, 'genre': 'other', 'long-name': 'Tax revenue violation'},
    'animal-cruelty-to': {'severity': 0, 'genre': 'other', 'long-name': 'Cruelty to animals'},
    'illegal-dumping': {'severity': 0, 'genre': 'other', 'long-name': 'Illegal dumping'},
    'other-conservation-crime': {'severity': 0, 'genre': 'other', 'long-name': 'Other conversation offense'},
    'littering': {'severity': 0, 'genre': 'other', 'long-name': 'Littering'},
    'other-enviornment-animal-viol': {'severity': 0, 'genre': 'other', 'long-name': 'Other environmental or animal offense'},
    'animal-poss-of-dangerous': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of a dangerous animal'},
    'money-laundering': {'severity': 0, 'genre': 'other', 'long-name': 'Money laundering'},
    'crimes-against-person-other': {'severity': 0, 'genre': 'other', 'long-name': 'Crimes against a person - other'},
    'homicide-solicitation': {'severity': 0, 'genre': 'other', 'long-name': 'Solicitation to commit homicide'},
    'reckless-endangerment': {'severity': 0, 'genre': 'other', 'long-name': 'Reckless endangerment'},
    'disarming-a-peace-officer': {'severity': 0, 'genre': 'other', 'long-name': 'Disarming a peace officer'},
    'homicide-accessory-to': {'severity': 0, 'genre': 'other', 'long-name': 'Accessory to commit homicide'},
    'property-crimes-other': {'severity': 0, 'genre': 'other', 'long-name': 'Property crimes - other'},
    'morals-other-moral-off': {'severity': 0, 'genre': 'other', 'long-name': 'Morals / decency offense - other'},
    'public-order-crimes-other': {'severity': 0, 'genre': 'other', 'long-name': 'Public order offense - other'},
    'fireworks-possession': {'severity': 0, 'genre': 'other', 'long-name': 'Possession of fireworks'},
    'public-order-crimes-other': {'severity': 0, 'genre': 'other', 'long-name': 'Public order offense - other'},
    'accessory-conspiracy-to-crime': {'severity': 0, 'genre': 'other', 'long-name': 'Accessory / conspiracy to crime'},
}
# Here so we can reference URLS such as http://denvercrimes.com/caphill 
# and redirect requests to an actual page.
neighborhood_shortcut_lookup = {
    'athmar-park': 'athmar-park',
    'auraria': 'auraria',
    'baker': 'baker',
    'barnum': 'barnum',
    'barnum-west': 'barnum-west',
    'bear-valley': 'bear-valley',
    'belcaro': 'belcaro',
    'berkeley': 'berkeley',
    'caphill': 'capitol-hill',
    'cbd': 'cbd',
    'chaffee-park': 'chaffee-park',
    'cheesman-park': 'cheesman-park',
    'cherry-creek': 'cherry-creek',
    'city-park': 'city-park',
    'city-park-west': 'city-park-west',
    'civic-center': 'civic-center',
    'clayton': 'clayton',
    'cole': 'cole',
    'college-view-south-platte': 'college-view-south-platte',
    'congress-park': 'congress-park',
    'cory-merrill': 'cory-merrill',
    'dia': 'dia',
    'east-colfax': 'east-colfax',
    'elyria-swansea': 'elyria-swansea',
    'five-points': 'five-points',
    'gateway-green-valley-ranch': 'gateway-green-valley-ranch',
    'globeville': 'globeville',
    'goldsmith': 'goldsmith',
    'hale': 'hale',
    'hampden': 'hampden',
    'hampden-south': 'hampden-south',
    'harvey-park': 'harvey-park',
    'harvey-park-south': 'harvey-park-south',
    'highland': 'highland',
    'hilltop': 'hilltop',
    'indian-creek': 'indian-creek',
    'jefferson-park': 'jefferson-park',
    'kennedy': 'kennedy',
    'lincoln-park': 'lincoln-park',
    'lowry-field': 'lowry-field',
    'mar-lee': 'mar-lee',
    'marston': 'marston',
    'montbello': 'montbello',
    'montclair': 'montclair',
    'north-capitol-hill': 'north-capitol-hill',
    'northeast-park-hill': 'northeast-park-hill',
    'north-park-hill': 'north-park-hill',
    'overland': 'overland',
    'platt-park': 'platt-park',
    'regis': 'regis',
    'ruby-hill': 'ruby-hill',
    'skyland': 'skyland',
    'sloan-lake': 'sloan-lake',
    'southmoor-park': 'southmoor-park',
    'south-park-hill': 'south-park-hill',
    'speer': 'speer',
    'stapleton': 'stapleton',
    'sunnyside': 'sunnyside',
    'sun-valley': 'sun-valley',
    'union-station': 'union-station',
    'university-hills': 'university-hills',
    'university-park': 'university-park',
    'university': 'university',
    'valverde': 'valverde',
    'villa-park': 'villa-park',
    'virginia-village': 'virginia-village',
    'washington-park-west': 'washington-park-west',
    'washington-virginia-vale': 'washington-virginia-vale',
    'west-colfax': 'west-colfax',
    'west-highland': 'west-highland',
    'westwood': 'westwood',
    'whittier': 'whittier',
    'windsor': 'windsor'
}
crime_types = ['criminal-mischief-mtr-veh', 'burglary-residence-no-force', 'vehicular-eluding-no-chase', 'traf-other', 'aslt-agg-police-gun', 'weapon-unlawful-discharge-of', 'theft-other', 'forgery-other', 'drug-barbiturate-possess', 'robbery-car-jacking', 'forgery-poss-of-forged-inst', 'failure-to-appear', 'theft-stln-veh-const-eqpt', 'arson-vehicle', 'liquor-possession', 'robbery-bank', 'other-enviornment-animal-viol', 'sex-aslt-non-rape', 'police-false-information', 'pawn-broker-viol', 'drug-methampetamine-possess', 'criminal-mischief-graffiti', 'burglary-business-by-force', 'weapon-carrying-concealed', 'harassment-dv', 'forgery-counterfeit-of-obj', 'drug-opium-or-deriv-sell', 'aggravated-assault', 'drug-cocaine-possess', 'robbery-street', 'theft-unauth-use-of-ftd', 'sex-off-fail-to-register', 'weapon-other-viol', 'violation-of-custody-order', 'theft-parts-from-vehicle', 'window-peeping', 'escape', 'violation-of-court-order', 'harassment', 'drug-fraud-to-obtain', 'criminal-mischief-other', 'theft-pick-pocket', 'bomb-threat', 'drug-hallucinogen-sell', 'aggravated-assault-dv', 'burglary-safe', 'arson-other', 'drug-poss-paraphernalia', 'theft-fail-return-rent-veh', 'theft-gas-drive-off', 'weapon-carrying-prohibited', 'weapon-by-prev-offender-powpo', 'theft-from-bldg', 'criminal-trespassing', 'liquor-misrepresent-age-minor', 'police-disobey-lawful-order', 'fraud-by-use-of-computer', 'burg-auto-theft-resd-w-force', 'drug-pcs-other-drug', 'drug-methampetamine-sell', 'burg-auto-theft-busn-w-force', 'impersonation-of-police', 'drug-marijuana-possess', 'theft-shoplift', 'assault-dv', 'fraud-identity-theft', 'theft-purse-snatch-no-force', 'drug-forgery-to-obtain', 'kidnap-dv', 'false-imprisonment', 'illegal-dumping', 'disturbing-the-peace', 'burg-auto-theft-resd-no-force', 'obstructing-govt-operation', 'public-fighting', 'police-making-a-false-rpt', 'weapon-poss-illegal-dangerous', 'indecent-exposure', 'harassment-sexual-in-nature', 'threats-to-injure', 'fireworks-possession', 'vehicular-eluding', 'drug-methamphetamine-mfr', 'weapon-fire-into-occ-veh', 'homicide-other', 'drug-hallucinogen-possess', 'violation-of-restraining-order', 'property-crimes-other', 'menacing-felony-w-weap', 'traf-vehicular-assault', 'theft-items-from-vehicle', 'theft-from-mails', 'sex-aslt-fondle-adult-victim', 'fraud-by-telephone', 'theft-of-motor-vehicle', 'stolen-property-buy-sell-rec', 'agg-aslt-police-weapon', 'robbery-purse-snatch-w-force', 'burg-auto-theft-busn-no-force', 'assault-police-simple', 'fraud-nsf-closed-account', 'theft-of-services', 'drug-heroin-sell', 'burglary-poss-of-tools', 'weapon-fire-into-occ-bldg', 'sex-aslt-rape', 'forgery-checks', 'fraud-criminal-impersonation', 'public-order-crimes-other', 'prostitution-engaging-in', 'burglary-residence-by-force', 'assault-simple', 'drug-cocaine-sell', 'theft-bicycle', 'animal-cruelty-to', 'arson-residence', 'traf-habitual-offender', 'drug-synth-narcotic-possess', 'police-resisting-arrest', 'kidnap-adult-victim', 'drug-make-sell-other-drug', 'burglary-vending-machine', 'police-obstruct-investigation', 'weapon-flourishing', 'drug-marijuana-sell', 'intimidation-of-a-witness', 'extortion', 'harassment-stalking-dv', 'robbery-business', 'burglary-business-no-force', 'contraband-into-prison', 'contraband-possession', 'traf-impound-vehicle', 'drug-heroin-possess', 'police-interference', 'theft-embezzle', 'explosive-incendiary-dev-pos', 'robbery-residence', 'theft-stln-vehicle-trailer']
keys = ['INCIDENT_ID','OFFENSE_ID','OFFENSE_CODE','OFFENSE_CODE_EXTENSION','OFFENSE_TYPE_ID','OFFENSE_CATEGORY_ID','FIRST_OCCURRENCE_DATE','LAST_OCCURRENCE_DATE','REPORTED_DATE','INCIDENT_ADDRESS','GEO_X','GEO_Y','GEO_LON','GEO_LAT','DISTRICT_ID','PRECINCT_ID','NEIGHBORHOOD_ID']
neighborhoods = ['wellshire', 'bear-valley', 'hilltop', 'cbd', 'university-hills', 'overland', 'speer', 'union-station', 'washington-virginia-vale', 'marston', 'north-capitol-hill', 'city-park', 'sloan-lake', 'five-points', 'sun-valley', 'westwood', 'cole', 'windsor', 'platt-park', 'jefferson-park', 'harvey-park', 'skyland', 'sunnyside', 'southmoor-park', 'ruby-hill', 'capitol-hill', 'barnum-west', 'harvey-park-south', 'dia', 'athmar-park', 'elyria-swansea', 'lowry-field', 'goldsmith', 'stapleton', 'chaffee-park', 'berkeley', 'washington-park', 'indian-creek', 'barnum', 'montbello', 'civic-center', 'hampden-south', 'globeville', 'city-park-west', 'clayton', 'northeast-park-hill', 'country-club', 'hale', 'mar-lee', 'lincoln-park', 'gateway-green-valley-ranch', 'west-highland', 'congress-park', 'regis', 'east-colfax', 'whittier', 'belcaro', 'hampden', 'fort-logan', 'college-view-south-platte', 'montclair', 'baker', 'kennedy', 'cherry-creek', 'cheesman-park', 'west-colfax', 'south-park-hill', 'cory-merrill', 'rosedale', 'valverde', 'university-park', 'auraria', 'north-park-hill', 'highland', 'villa-park', 'university', 'virginia-village', 'washington-park-west']
populations = {'wellshire': '3133', 'cbd': '3648', 'university-hills': '5327', 'overland': '2218', 'speer': '10954', 'gateway-green-valley-ranch': '29201', 'ruby-hill': '9820', 'marston': '11132', 'north-capitol-hill': '5823', 'city-park': '2907', 'indian-creek': '3096', 'five-points': '12712', 'sun-valley': '1448', 'westwood': '15486', 'cole': '4651', 'washington-park-west': '6393', 'platt-park': '5393', 'harvey-park-south': '8393', 'villa-park': '8758', 'athmar-park': '8898', 'skyland': '3106', 'north-park-hill': '9382', 'sunnyside': '9726', 'southmoor-park': '3826', 'jefferson-park': '2552', 'capitol-hill': '14708', 'windsor': '12589', 'barnum-west': '5376', 'virginia-village': '12844', 'montbello': '30348', 'bear-valley': '8889', 'goldsmith': '5808', 'stapleton': '13948', 'chaffee-park': '3874', 'cory-merrill': '3892', 'northeast-park-hill': '7822', 'union-station': '4348', 'washington-park': '6905', 'barnum': '6111', 'elyria-swansea': '6401', 'civic-center': '1577', 'hampden-south': '14370', 'globeville': '3687', 'city-park-west': '4844', 'clayton': '4336', 'cheesman-park': '7971', 'country-club': '3001', 'hale': '6936', 'mar-lee': '12452', 'lincoln-park': '6119', 'berkeley': '8112', 'west-highland': '8540', 'harvey-park': '11525', 'regis': '3934', 'east-colfax': '10191', 'whittier': '4831', 'belcaro': '4172', 'hampden': '17547', 'fort-logan': '8532', 'college-view-south-platte': '6498', 'west-colfax': '9740', 'baker': '4879', 'kennedy': '4464', 'cherry-creek': '5589', 'dia': '1165', 'congress-park': '10235', 'south-park-hill': '8590', 'rosedale': '2553', 'valverde': '3941', 'lowry-field': '8067', 'washington-virginia-vale': '13030', 'auraria': '705', 'hilltop': '8190', 'highland': '8429', 'montclair': '5456', 'university': '9375', 'university-park': '7491', 'sloan-lake': '7238'}

