crime_genres = ['violent', 'property', 'other']
crime_lookup_reverse = { 
    'violent': ['murder', 'robbery', 'aggravated-assault', 'sexual-assault'],
    'property': ['arson', 'theft-from-motor-vehicle', 'auto-theft', 'burglary', 'larceny'],
    'other': ['all-other-crimes', 'drug-alcohol', 'other-crimes-against-persons', 'white-collar-crime', 'public-disorder'] }
crime_lookup = {
    'all-other-crimes': 'other',
    'murder': 'violent',
    'arson': 'property',
    'theft-from-motor-vehicle': 'property',
    'auto-theft': 'property',
    'sexual-assault': 'violent',
    'drug-alcohol': 'other',
    'larceny': 'property',
    'aggravated-assault': 'violent',
    'other-crimes-against-persons': 'other',
    'robbery': 'violent',
    'burglary': 'property',
    'white-collar-crime': 'other',
    'public-disorder': 'other'
}
neighborhood_lookup = {
    'athmar-park': {'full': 'Athmar Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'auraria': {'full': 'Auraria', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'baker': {'full': 'Baker', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'barnum': {'full': 'Barnum', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'barnum-west': {'full': 'Barnum West', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'bear-valley': {'full': 'Bear Valley', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'belcaro': {'full': 'Belcaro', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'berkeley': {'full': 'Berkeley', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'capitol-hill': {'full': 'Capitol Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cbd': {'full': 'CBD', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'chaffee-park': {'full': 'Chaffee Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cheesman-park': {'full': 'Cheesman Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cherry-creek': {'full': 'Cherry Creek', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'city-park': {'full': 'City Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'city-park-west': {'full': 'City Park West', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'civic-center': {'full': 'Civic Center', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'clayton': {'full': 'Clayton', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cole': {'full': 'Cole', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'college-view-south-platte': {'full': 'College View South Platte', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'congress-park': {'full': 'Congress Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'cory-merrill': {'full': 'Cory Merrill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'dia': {'full': 'DIA', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'east-colfax': {'full': 'East Colfax', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'elyria-swansea': {'full': 'Elyria Swansea', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'five-points': {'full': 'Five Points', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'gateway-green-valley-ranch': {'full': 'Gateway Green Valley Ranch', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'globeville': {'full': 'Globeville', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'goldsmith': {'full': 'Goldsmith', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'hale': {'full': 'Hale', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'hampden': {'full': 'Hampden', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'hampden-south': {'full': 'Hampden South', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'harvey-park': {'full': 'Harvey Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'harvey-park-south': {'full': 'Harvey Park South', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'highland': {'full': 'Highland', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'hilltop': {'full': 'Hilltop', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'indian-creek': {'full': 'Indian Creek', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'jefferson-park': {'full': 'Jefferson Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'kennedy': {'full': 'Kennedy', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'lincoln-park': {'full': 'Lincoln Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'lowry-field': {'full': 'Lowry Field', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'mar-lee': {'full': 'Mar Lee', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'marston': {'full': 'Marston', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'montbello': {'full': 'Montbello', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'montclair': {'full': 'Montclair', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'north-capitol-hill': {'full': 'North Capitol Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'northeast-park-hill': {'full': 'Northeast Park Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'north-park-hill': {'full': 'North Park Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'overland': {'full': 'Overland', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'platt-park': {'full': 'Platt Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'regis': {'full': 'Regis', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'ruby-hill': {'full': 'Ruby Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'skyland': {'full': 'Skyland', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'sloan-lake': {'full': 'Sloan Lake', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'southmoor-park': {'full': 'Southmoor Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'south-park-hill': {'full': 'South Park Hill', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'speer': {'full': 'Speer', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'stapleton': {'full': 'Stapleton', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'sunnyside': {'full': 'Sunnyside', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'sun-valley': {'full': 'Sun Valley', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'union-station': {'full': 'Union Station', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'university': {'full': 'University', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'university-hills': {'full': 'University Hills', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'university-park': {'full': 'University Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'valverde': {'full': 'Valverde', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'villa-park': {'full': 'Villa Park', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'virginia-village': {'full': 'Virginia Village', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'washington-park-west': {'full': 'Washington Park West', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'washington-virginia-vale': {'full': 'Washington Virginia Vale', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'west-colfax': {'full': 'West Colfax', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'west-highland': {'full': 'West Highland', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'westwood': {'full': 'Westwood', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'whittier': {'full': 'Whittier', 'nearest_neighbors': {}, 'location': {}, 'population': 0},
    'windsor': {'full': 'Windsor', 'nearest_neighbors': {}, 'location': {}, 'population': 0}
}
# Here so we can reference URLS such as http://denvercrimes.com/caphill 
# and redirect requests to an actual page.
neighborhood_shortcut_lookup = {
    'athmar-park': 'athmar-park',
    'auraria': 'auraria',
    'baker': 'baker',
    'barnum': 'barnum',
    'barnum-west': 'barnum-west',
    'bear-valley': 'bear-valley',
    'belcaro': 'belcaro',
    'berkeley': 'berkeley',
    'caphill': 'capitol-hill',
    'cbd': 'cbd',
    'chaffee-park': 'chaffee-park',
    'cheesman-park': 'cheesman-park',
    'cherry-creek': 'cherry-creek',
    'city-park': 'city-park',
    'city-park-west': 'city-park-west',
    'civic-center': 'civic-center',
    'clayton': 'clayton',
    'cole': 'cole',
    'college-view-south-platte': 'college-view-south-platte',
    'congress-park': 'congress-park',
    'cory-merrill': 'cory-merrill',
    'dia': 'dia',
    'east-colfax': 'east-colfax',
    'elyria-swansea': 'elyria-swansea',
    'five-points': 'five-points',
    'gateway-green-valley-ranch': 'gateway-green-valley-ranch',
    'globeville': 'globeville',
    'goldsmith': 'goldsmith',
    'hale': 'hale',
    'hampden': 'hampden',
    'hampden-south': 'hampden-south',
    'harvey-park': 'harvey-park',
    'harvey-park-south': 'harvey-park-south',
    'highland': 'highland',
    'hilltop': 'hilltop',
    'indian-creek': 'indian-creek',
    'jefferson-park': 'jefferson-park',
    'kennedy': 'kennedy',
    'lincoln-park': 'lincoln-park',
    'lowry-field': 'lowry-field',
    'mar-lee': 'mar-lee',
    'marston': 'marston',
    'montbello': 'montbello',
    'montclair': 'montclair',
    'north-capitol-hill': 'north-capitol-hill',
    'northeast-park-hill': 'northeast-park-hill',
    'north-park-hill': 'north-park-hill',
    'overland': 'overland',
    'platt-park': 'platt-park',
    'regis': 'regis',
    'ruby-hill': 'ruby-hill',
    'skyland': 'skyland',
    'sloan-lake': 'sloan-lake',
    'southmoor-park': 'southmoor-park',
    'south-park-hill': 'south-park-hill',
    'speer': 'speer',
    'stapleton': 'stapleton',
    'sunnyside': 'sunnyside',
    'sun-valley': 'sun-valley',
    'union-station': 'union-station',
    'university-hills': 'university-hills',
    'university-park': 'university-park',
    'university': 'university',
    'valverde': 'valverde',
    'villa-park': 'villa-park',
    'virginia-village': 'virginia-village',
    'washington-park-west': 'washington-park-west',
    'washington-virginia-vale': 'washington-virginia-vale',
    'west-colfax': 'west-colfax',
    'west-highland': 'west-highland',
    'westwood': 'westwood',
    'whittier': 'whittier',
    'windsor': 'windsor'
}
crime_types = ['criminal-mischief-mtr-veh', 'burglary-residence-no-force', 'vehicular-eluding-no-chase', 'traf-other', 'aslt-agg-police-gun', 'weapon-unlawful-discharge-of', 'theft-other', 'forgery-other', 'drug-barbiturate-possess', 'robbery-car-jacking', 'forgery-poss-of-forged-inst', 'failure-to-appear', 'theft-stln-veh-const-eqpt', 'arson-vehicle', 'liquor-possession', 'robbery-bank', 'other-enviornment-animal-viol', 'sex-aslt-non-rape', 'police-false-information', 'pawn-broker-viol', 'drug-methampetamine-possess', 'criminal-mischief-graffiti', 'burglary-business-by-force', 'weapon-carrying-concealed', 'harassment-dv', 'forgery-counterfeit-of-obj', 'drug-opium-or-deriv-sell', 'aggravated-assault', 'drug-cocaine-possess', 'robbery-street', 'theft-unauth-use-of-ftd', 'sex-off-fail-to-register', 'weapon-other-viol', 'violation-of-custody-order', 'theft-parts-from-vehicle', 'window-peeping', 'escape', 'violation-of-court-order', 'harassment', 'drug-fraud-to-obtain', 'criminal-mischief-other', 'theft-pick-pocket', 'bomb-threat', 'drug-hallucinogen-sell', 'aggravated-assault-dv', 'burglary-safe', 'arson-other', 'drug-poss-paraphernalia', 'theft-fail-return-rent-veh', 'theft-gas-drive-off', 'weapon-carrying-prohibited', 'weapon-by-prev-offender-powpo', 'theft-from-bldg', 'criminal-trespassing', 'liquor-misrepresent-age-minor', 'police-disobey-lawful-order', 'fraud-by-use-of-computer', 'burg-auto-theft-resd-w-force', 'drug-pcs-other-drug', 'drug-methampetamine-sell', 'burg-auto-theft-busn-w-force', 'impersonation-of-police', 'drug-marijuana-possess', 'theft-shoplift', 'assault-dv', 'fraud-identity-theft', 'theft-purse-snatch-no-force', 'drug-forgery-to-obtain', 'kidnap-dv', 'false-imprisonment', 'illegal-dumping', 'disturbing-the-peace', 'burg-auto-theft-resd-no-force', 'obstructing-govt-operation', 'public-fighting', 'police-making-a-false-rpt', 'weapon-poss-illegal-dangerous', 'indecent-exposure', 'harassment-sexual-in-nature', 'threats-to-injure', 'fireworks-possession', 'vehicular-eluding', 'drug-methamphetamine-mfr', 'weapon-fire-into-occ-veh', 'homicide-other', 'drug-hallucinogen-possess', 'violation-of-restraining-order', 'property-crimes-other', 'menacing-felony-w-weap', 'traf-vehicular-assault', 'theft-items-from-vehicle', 'theft-from-mails', 'sex-aslt-fondle-adult-victim', 'fraud-by-telephone', 'theft-of-motor-vehicle', 'stolen-property-buy-sell-rec', 'agg-aslt-police-weapon', 'robbery-purse-snatch-w-force', 'burg-auto-theft-busn-no-force', 'assault-police-simple', 'fraud-nsf-closed-account', 'theft-of-services', 'drug-heroin-sell', 'burglary-poss-of-tools', 'weapon-fire-into-occ-bldg', 'sex-aslt-rape', 'forgery-checks', 'fraud-criminal-impersonation', 'public-order-crimes-other', 'prostitution-engaging-in', 'burglary-residence-by-force', 'assault-simple', 'drug-cocaine-sell', 'theft-bicycle', 'animal-cruelty-to', 'arson-residence', 'traf-habitual-offender', 'drug-synth-narcotic-possess', 'police-resisting-arrest', 'kidnap-adult-victim', 'drug-make-sell-other-drug', 'burglary-vending-machine', 'police-obstruct-investigation', 'weapon-flourishing', 'drug-marijuana-sell', 'intimidation-of-a-witness', 'extortion', 'harassment-stalking-dv', 'robbery-business', 'burglary-business-no-force', 'contraband-into-prison', 'contraband-possession', 'traf-impound-vehicle', 'drug-heroin-possess', 'police-interference', 'theft-embezzle', 'explosive-incendiary-dev-pos', 'robbery-residence', 'theft-stln-vehicle-trailer']
keys = ['INCIDENT_ID','OFFENSE_ID','OFFENSE_CODE','OFFENSE_CODE_EXTENSION','OFFENSE_TYPE_ID','OFFENSE_CATEGORY_ID','FIRST_OCCURRENCE_DATE','LAST_OCCURRENCE_DATE','REPORTED_DATE','INCIDENT_ADDRESS','GEO_X','GEO_Y','GEO_LON','GEO_LAT','DISTRICT_ID','PRECINCT_ID','NEIGHBORHOOD_ID']
neighborhoods = ['wellshire', 'bear-valley', 'hilltop', 'cbd', 'university-hills', 'overland', 'speer', 'union-station', 'washington-virginia-vale', 'marston', 'north-capitol-hill', 'city-park', 'sloan-lake', 'five-points', 'sun-valley', 'westwood', 'cole', 'windsor', 'platt-park', 'jefferson-park', 'harvey-park', 'skyland', 'sunnyside', 'southmoor-park', 'ruby-hill', 'capitol-hill', 'barnum-west', 'harvey-park-south', 'dia', 'athmar-park', 'elyria-swansea', 'lowry-field', 'goldsmith', 'stapleton', 'chaffee-park', 'berkeley', 'washington-park', 'indian-creek', 'barnum', 'montbello', 'civic-center', 'hampden-south', 'globeville', 'city-park-west', 'clayton', 'northeast-park-hill', 'country-club', 'hale', 'mar-lee', 'lincoln-park', 'gateway-green-valley-ranch', 'west-highland', 'congress-park', 'regis', 'east-colfax', 'whittier', 'belcaro', 'hampden', 'fort-logan', 'college-view-south-platte', 'montclair', 'baker', 'kennedy', 'cherry-creek', 'cheesman-park', 'west-colfax', 'south-park-hill', 'cory-merrill', 'rosedale', 'valverde', 'university-park', 'auraria', 'north-park-hill', 'highland', 'villa-park', 'university', 'virginia-village', 'washington-park-west']
populations = {'wellshire': '3133', 'cbd': '3648', 'university-hills': '5327', 'overland': '2218', 'speer': '10954', 'gateway-green-valley-ranch': '29201', 'ruby-hill': '9820', 'marston': '11132', 'north-capitol-hill': '5823', 'city-park': '2907', 'indian-creek': '3096', 'five-points': '12712', 'sun-valley': '1448', 'westwood': '15486', 'cole': '4651', 'washington-park-west': '6393', 'platt-park': '5393', 'harvey-park-south': '8393', 'villa-park': '8758', 'athmar-park': '8898', 'skyland': '3106', 'north-park-hill': '9382', 'sunnyside': '9726', 'southmoor-park': '3826', 'jefferson-park': '2552', 'capitol-hill': '14708', 'windsor': '12589', 'barnum-west': '5376', 'virginia-village': '12844', 'montbello': '30348', 'bear-valley': '8889', 'goldsmith': '5808', 'stapleton': '13948', 'chaffee-park': '3874', 'cory-merrill': '3892', 'northeast-park-hill': '7822', 'union-station': '4348', 'washington-park': '6905', 'barnum': '6111', 'elyria-swansea': '6401', 'civic-center': '1577', 'hampden-south': '14370', 'globeville': '3687', 'city-park-west': '4844', 'clayton': '4336', 'cheesman-park': '7971', 'country-club': '3001', 'hale': '6936', 'mar-lee': '12452', 'lincoln-park': '6119', 'berkeley': '8112', 'west-highland': '8540', 'harvey-park': '11525', 'regis': '3934', 'east-colfax': '10191', 'whittier': '4831', 'belcaro': '4172', 'hampden': '17547', 'fort-logan': '8532', 'college-view-south-platte': '6498', 'west-colfax': '9740', 'baker': '4879', 'kennedy': '4464', 'cherry-creek': '5589', 'dia': '1165', 'congress-park': '10235', 'south-park-hill': '8590', 'rosedale': '2553', 'valverde': '3941', 'lowry-field': '8067', 'washington-virginia-vale': '13030', 'auraria': '705', 'hilltop': '8190', 'highland': '8429', 'montclair': '5456', 'university': '9375', 'university-park': '7491', 'sloan-lake': '7238'}

