# Some information about how this all was put together would be useful.
environ = 'DEV'
crime_genres = ['violent', 'property', 'other']
crime_lookup_reverse = { 
    'violent': ['murder', 'robbery', 'aggravated-assault', 'sexual-assault'],
    'property': ['arson', 'theft-from-motor-vehicle', 'auto-theft', 'burglary', 'larceny'],
    'other': ['all-other-crimes', 'drug-alcohol', 'other-crimes-against-persons', 'white-collar-crime', 'public-disorder'],
    'traffic': ['traffic-accident']
}
crime_lookup = {
    'traffic-accident': 'traffic',
    'all-other-crimes': 'other',
    'murder': 'violent',
    'arson': 'property',
    'theft-from-motor-vehicle': 'property',
    'auto-theft': 'property',
    'sexual-assault': 'violent',
    'drug-alcohol': 'other',
    'larceny': 'property',
    'aggravated-assault': 'violent',
    'other-crimes-against-persons': 'other',
    'robbery': 'violent',
    'burglary': 'property',
    'white-collar-crime': 'other',
    'public-disorder': 'other'
}
neighborhood_lookup = {
    'athmar-park': {'full': 'Athmar Park', 'adjacent-neighbors': {}, 'nearest_neighbors': {'valverde', 'baker', 'ruby-hill', 'westwood'}, 'location': {}, 'population': 0},
    'auraria': {'full': 'Auraria', 'adjacent-neighbors': {}, 'nearest_neighbors': {'highland', 'union-station', 'cbd', 'lincoln-park', 'sun-valley'}, 'location': {}, 'population': 0},
    'baker': {'full': 'Baker', 'adjacent-neighbors': {}, 'nearest_neighbors': {'lincoln-park', 'speer', 'washington-park-west', 'overland', 'athmar-park', 'valverde'}, 'location': {}, 'population': 0},
    'barnum': {'full': 'Barnum', 'adjacent-neighbors': {}, 'nearest_neighbors': {'villa-park', 'barnum-west', 'valverde', 'westwood'}, 'location': {}, 'population': 0},
    'barnum-west': {'full': 'Barnum West', 'adjacent-neighbors': {}, 'nearest_neighbors': {'villa-park', 'barnum', 'westwood'}, 'location': {}, 'population': 0},
    'bear-valley': {'full': 'Bear Valley', 'adjacent-neighbors': {}, 'nearest_neighbors': {'harvey-park-south', 'fort-logan'}, 'location': {}, 'population': 0},
    'belcaro': {'full': 'Belcaro', 'adjacent-neighbors': {}, 'nearest_neighbors': {'washington-park', 'cherry-creek', 'cory-merrill'}, 'location': {}, 'population': 0},
    'berkeley': {'full': 'Berkeley', 'adjacent-neighbors': {'chaffee-park', 'highland'}, 'nearest_neighbors': {'regis', 'sunnyside', 'west-highland'}, 'location': {}, 'population': 0},
    'capitol-hill': {'full': 'Capitol Hill', 'adjacent-neighbors': {'cbd', 'city-park-west'}, 'nearest_neighbors': {'north-capitol-hill', 'civic-center', 'cheesman-park', 'speer', 'country-club'}, 'location': {}, 'population': 0},
    'cbd': {'full': 'CBD', 'adjacent-neighbors': {'capitol-hill'}, 'nearest_neighbors': {'auraria', 'union-station', 'five-points', 'north-capitol-hill', 'civic-center'}, 'location': {}, 'population': 0},
    'chaffee-park': {'full': 'Chaffee Park', 'adjacent-neighbors': {'berkeley'}, 'nearest_neighbors': {'regis', 'sunnyside', 'globeville'}, 'location': {}, 'population': 0},
    'cheesman-park': {'full': 'Cheesman Park', 'adjacent-neighbors': {'north-capitol-hill', 'city-park'}, 'nearest_neighbors': {'capitol-hill', 'city-park-west', 'congress-park', 'country-club'}, 'location': {}, 'population': 0},
    'cherry-creek': {'full': 'Cherry Creek', 'adjacent-neighbors': {}, 'nearest_neighbors': {'congress-park', 'hilltop', 'belcaro', 'country-club'}, 'location': {}, 'population': 0},
    'city-park': {'full': 'City Park', 'adjacent-neighbors': {'whittier', 'hale', 'north-park-hill', 'cheesman-park'}, 'nearest_neighbors': {'congress-park', 'city-park-west', 'skyland', 'south-park-hill'}, 'location': {}, 'population': 0},
    'city-park-west': {'full': 'City Park West', 'adjacent-neighbors': {'capitol-hill', 'congress-park', 'skyland'}, 'nearest_neighbors': {'north-capitol-hill', 'five-points', 'whittier', 'city-park', 'cheesman-park'}, 'location': {}, 'population': 0},
    'civic-center': {'full': 'Civic Center', 'adjacent-neighbors': {'north-capitol-hill', 'baker'}, 'nearest_neighbors': {'cbd', 'capitol-hill', 'lincoln-park'}, 'location': {}, 'population': 0},
    'clayton': {'full': 'Clayton', 'adjacent-neighbors': {'whittier'}, 'nearest_neighbors': {'elyria-swansea', 'northeast-park-hill', 'skyland', 'cole'}, 'location': {}, 'population': 0},
    'cole': {'full': 'Cole', 'adjacent-neighbors': {'skyland'}, 'nearest_neighbors': {'elyria-swansea', 'clayton', 'whittier', 'five-points'}, 'location': {}, 'population': 0},
    'college-view-south-platte': {'full': 'College View South Platte', 'adjacent-neighbors': {}, 'nearest_neighbors': {'harvey-park-south', 'harvey-park', 'ruby-hill', 'overland'}, 'location': {}, 'population': 0},
    'congress-park': {'full': 'Congress Park', 'adjacent-neighbors': {'city-park-west', 'south-park-hill', 'hilltop'}, 'nearest_neighbors': {'cheesman-park', 'city-park', 'hale', 'cherry-creek', 'country-club'}, 'location': {}, 'population': 0},
    'cory-merrill': {'full': 'Cory Merrill', 'adjacent-neighbors': {}, 'nearest_neighbors': {'washington-park', 'belcaro', 'virginia-village', 'university-park'}, 'location': {}, 'population': 0},
    'country-club': {'full': 'Country Club', 'adjacent-neighbors': {}, 'nearest_neighbors': {'capitol-hill', 'cheesman-park', 'congress-park', 'cherry-creek', 'washington-park', 'speer'}, 'location': {}, 'population': 0},
    'dia': {'full': 'DIA', 'adjacent-neighbors': {}, 'nearest_neighbors': {'gateway-green-valley-ranch'}, 'location': {}, 'population': 0},
    'east-colfax': {'full': 'East Colfax', 'adjacent-neighbors': {}, 'nearest_neighbors': {'stapleton', 'lowry-field', 'montclair', 'south-park-hill'}, 'location': {}, 'population': 0},
    'elyria-swansea': {'full': 'Elyria Swansea', 'adjacent-neighbors': {}, 'nearest_neighbors': {'globeville', 'northeast-park-hill', 'clayton', 'cole', 'five-points'}, 'location': {}, 'population': 0},
    'five-points': {'full': 'Five Points', 'adjacent-neighbors': {}, 'nearest_neighbors': {'highland', 'globeville', 'elyria-swansea', 'cole', 'whittier', 'city-park-west', 'north-capitol-hill', 'cbd', 'union-station'}, 'location': {}, 'population': 0},
    'fort-logan': {'full': 'Fort Logan', 'adjacent-neighbors': {}, 'nearest_neighbors': {'bear-valley', 'harvey-park-south', 'marston'}, 'location': {}, 'population': 0},
    'gateway-green-valley-ranch': {'full': 'Gateway Green Valley Ranch', 'adjacent-neighbors': {}, 'nearest_neighbors': {'montbello', 'dia'}, 'location': {}, 'population': 0},
    'globeville': {'full': 'Globeville', 'adjacent-neighbors': {}, 'nearest_neighbors': {'elyria-swansea', 'five-points', 'highland', 'sunnyside', 'chaffee-park'}, 'location': {}, 'population': 0},
    'goldsmith': {'full': 'Goldsmith', 'adjacent-neighbors': {}, 'nearest_neighbors': {'virginia-village', 'hampden'}, 'location': {}, 'population': 0},
    'hale': {'full': 'Hale', 'adjacent-neighbors': {}, 'nearest_neighbors': {'congress-park', 'south-park-hill', 'montclair', 'hilltop'}, 'location': {}, 'population': 0},
    'hampden': {'full': 'Hampden', 'adjacent-neighbors': {}, 'nearest_neighbors': {'goldsmith', 'hampden-south', 'university-hills'}, 'location': {}, 'population': 0},
    'hampden-south': {'full': 'Hampden South', 'adjacent-neighbors': {}, 'nearest_neighbors': {'southmoor-park', 'hampden'}, 'location': {}, 'population': 0},
    'harvey-park': {'full': 'Harvey Park', 'adjacent-neighbors': {}, 'nearest_neighbors': {'mar-lee', 'college-view-south-platte', 'harvey-park-south'}, 'location': {}, 'population': 0},
    'harvey-park-south': {'full': 'Harvey Park South', 'adjacent-neighbors': {}, 'nearest_neighbors': {'harvey-park', 'college-view-south-platte', 'bear-valley', 'fort-logan'}, 'location': {}, 'population': 0},
    'highland': {'full': 'Highland', 'adjacent-neighbors': {'auraria', 'berkeley', 'sloan-lake'}, 'nearest_neighbors': {'sunnyside', 'west-highland', 'jefferson-park', 'union-station', 'five-points', 'globeville'}, 'location': {}, 'population': 0},
    'hilltop': {'full': 'Hilltop', 'adjacent-neighbors': {}, 'nearest_neighbors': {'hale', 'montclair', 'lowry-field', 'washington-virginia-vale', 'cherry-creek'}, 'location': {}, 'population': 0},
    'indian-creek': {'full': 'Indian Creek', 'adjacent-neighbors': {}, 'nearest_neighbors': {'washington-virginia-vale', 'virginia-village'}, 'location': {}, 'population': 0},
    'jefferson-park': {'full': 'Jefferson Park', 'adjacent-neighbors': {'west-colfax', 'west-highland', 'union-station'}, 'nearest_neighbors': {'sloan-lake', 'highland', 'auraria', 'sun-valley'}, 'location': {}, 'population': 0},
    'kennedy': {'full': 'Kennedy', 'adjacent-neighbors': {}, 'nearest_neighbors': {'hampden'}, 'location': {}, 'population': 0},
    'lincoln-park': {'full': 'Lincoln Park', 'adjacent-neighbors': {'valverde', 'speer'}, 'nearest_neighbors': {'sun-valley', 'auraria', 'civic-center', 'baker'}, 'location': {}, 'population': 0},
    'lowry-field': {'full': 'Lowry Field', 'adjacent-neighbors': {}, 'nearest_neighbors': {'east-colfax', 'montclair', 'hilltop', 'washington-virginia-vale', 'windsor'}, 'location': {}, 'population': 0},
    'mar-lee': {'full': 'Mar Lee', 'adjacent-neighbors': {}, 'nearest_neighbors': {'westwood', 'ruby-hill', 'harvey-park'}, 'location': {}, 'population': 0},
    'marston': {'full': 'Marston', 'adjacent-neighbors': {}, 'nearest_neighbors': {'fort-logan'}, 'location': {}, 'population': 0},
    'montbello': {'full': 'Montbello', 'adjacent-neighbors': {}, 'nearest_neighbors': {'stapleton', 'gateway-green-valley-ranch'}, 'location': {}, 'population': 0},
    'montclair': {'full': 'Montclair', 'adjacent-neighbors': {}, 'nearest_neighbors': {'hale', 'south-park-hill', 'east-colfax', 'lowry-field', 'hilltop'}, 'location': {}, 'population': 0},
    'north-capitol-hill': {'full': 'North Capitol Hill', 'adjacent-neighbors': {'civic-center', 'cheesman-park'}, 'nearest_neighbors': {'capitol-hill', 'cbd', 'five-points', 'city-park-west', }, 'location': {}, 'population': 0},
    'northeast-park-hill': {'full': 'Northeast Park Hill', 'adjacent-neighbors': {}, 'nearest_neighbors': {'elyria-swansea', 'stapleton', 'north-park-hill', 'clayton'}, 'location': {}, 'population': 0},
    'north-park-hill': {'full': 'North Park Hill', 'adjacent-neighbors': {}, 'nearest_neighbors': {'south-park-hill', 'skyland', 'northeast-park-hill', 'stapleton'}, 'location': {}, 'population': 0},
    'overland': {'full': 'Overland', 'adjacent-neighbors': {}, 'nearest_neighbors': {'baker', 'platt-park', 'rosedale', 'college-view-south-platte', 'ruby-hill'}, 'location': {}, 'population': 0},
    'platt-park': {'full': 'Platt Park', 'adjacent-neighbors': {}, 'nearest_neighbors': {'washington-park-west', 'university', 'rosedale', 'overland'}, 'location': {}, 'population': 0},
    'regis': {'full': 'Regis', 'adjacent-neighbors': {'sunnyside'}, 'nearest_neighbors': {'chaffee-park', 'berkeley'}, 'location': {}, 'population': 0},
    'rosedale': {'full': 'Rosedale', 'adjacent-neighbors': {}, 'nearest_neighbors': {'overland', 'platt-park', 'university'}, 'location': {}, 'population': 0},
    'ruby-hill': {'full': 'Ruby Hill', 'adjacent-neighbors': {}, 'nearest_neighbors': {'athmar-park', 'overland', 'college-view-south-platte', 'mar-lee'}, 'location': {}, 'population': 0},
    'skyland': {'full': 'Skyland', 'adjacent-neighbors': {'cole', 'south-park-hill'}, 'nearest_neighbors': {'clayton', 'north-park-hill', 'city-park', 'whittier'}, 'location': {}, 'population': 0},
    'sloan-lake': {'full': 'Sloan Lake', 'adjacent-neighbors': {'highland', 'sun-valley'}, 'nearest_neighbors': {'west-highland', 'jefferson-park', 'west-colfax'}, 'location': {}, 'population': 0},
    'southmoor-park': {'full': 'Southmoor Park', 'adjacent-neighbors': {}, 'nearest_neighbors': {'university-hills', 'hampden-south'}, 'location': {}, 'population': 0},
    'south-park-hill': {'full': 'South Park Hill', 'adjacent-neighbors': {}, 'nearest_neighbors': {'north-park-hill', 'east-colfax', 'montclair', 'hale', 'city-park'}, 'location': {}, 'population': 0},
    'speer': {'full': 'Speer', 'adjacent-neighbors': {}, 'nearest_neighbors': {'capitol-hill', 'country-club', 'washington-park', 'washington-park-west', 'baker'}, 'location': {}, 'population': 0},
    'stapleton': {'full': 'Stapleton', 'adjacent-neighbors': {}, 'nearest_neighbors': {'montbello', 'east-colfax', 'north-park-hill', 'northeast-park-hill'}, 'location': {}, 'population': 0},
    'sunnyside': {'full': 'Sunnyside', 'adjacent-neighbors': {'regis', 'west-highland'}, 'nearest_neighbors': {'chaffee', 'berkeley', 'globeville', 'highland'}, 'location': {}, 'population': 0},
    'sun-valley': {'full': 'Sun Valley', 'adjacent-neighbors': {'sloan-lake', 'barnum', 'baker'}, 'nearest_neighbors': {'villa-park', 'west-colfax', 'jefferson-park', 'auraria', 'lincoln-park', 'valverde'}, 'location': {}, 'population': 0},
    'union-station': {'full': 'Union Station', 'adjacent-neighbors': {'jefferson-park'}, 'nearest_neighbors': {'highland', 'five-points', 'cbd', 'auraria'}, 'location': {}, 'population': 0},
    'university': {'full': 'University', 'adjacent-neighbors': {}, 'nearest_neighbors': {'rosedale', 'platt-park', 'washington-park', 'university-park', 'wellshire'}, 'location': {}, 'population': 0},
    'university-hills': {'full': 'University Hills', 'adjacent-neighbors': {}, 'nearest_neighbors': {'university-park', 'wellshire', 'southmoor-park', 'hampden', 'goldsmith'}, 'location': {}, 'population': 0},
    'university-park': {'full': 'University Park', 'adjacent-neighbors': {}, 'nearest_neighbors': {'university', 'wellshire', 'cory-merrill', 'university-hills'}, 'location': {}, 'population': 0},
    'valverde': {'full': 'Valverde', 'adjacent-neighbors': {}, 'nearest_neighbors': {'sun-valley', 'baker', 'athmar-park', 'barnum'}, 'location': {}, 'population': 0},
    'villa-park': {'full': 'Villa Park', 'adjacent-neighbors': {'valverde'}, 'nearest_neighbors': {'west-colfax', 'sun-valley', 'barnum-west', 'barnum'}, 'location': {}, 'population': 0},
    'virginia-village': {'full': 'Virginia Village', 'adjacent-neighbors': {}, 'nearest_neighbors': {'washington-virginia-vale', 'indian-creek', 'goldsmith', 'cory-merrill'}, 'location': {}, 'population': 0},
    'washington-park': {'full': 'Washington Park', 'adjacent-neighbors': {}, 'nearest_neighbors': {'washington-park-west', 'speer', 'country-club', 'belcaro', 'cory-merrill', 'university'}, 'location': {}, 'population': 0},
    'washington-park-west': {'full': 'Washington Park West', 'adjacent-neighbors': {}, 'nearest_neighbors': {'baker', 'washington-park', 'speer', 'platt-park'}, 'location': {}, 'population': 0},
    'washington-virginia-vale': {'full': 'Washington Virginia Vale', 'adjacent-neighbors': {}, 'nearest_neighbors': {'hilltop', 'lowry-field', 'windsor', 'indian-creek', 'virginia-village', }, 'location': {}, 'population': 0},
    'wellshire': {'full': 'Wellshire', 'adjacent-neighbors': {}, 'nearest_neighbors': {'university', 'university-park', 'university-hills', }, 'location': {}, 'population': 0},
    'west-colfax': {'full': 'West Colfax', 'adjacent-neighbors': {'jefferson-park'}, 'nearest_neighbors': {'sloan-lake', 'sun-valley', 'villa-park'}, 'location': {}, 'population': 0},
    'west-highland': {'full': 'West Highland', 'adjacent-neighbors': {'sunnyside', 'jefferson-park'}, 'nearest_neighbors': {'berkeley', 'highland', 'sloan-lake'}, 'location': {}, 'population': 0},
    'westwood': {'full': 'Westwood', 'adjacent-neighbors': {}, 'nearest_neighbors': {'barnum-west', 'barnum', 'athmar-park', 'mar-lee'}, 'location': {}, 'population': 0},
    'whittier': {'full': 'Whittier', 'adjacent-neighbors': {'clayton', 'city-park'}, 'nearest_neighbors': {'five-points', 'cole', 'skyland', 'city-park-west'}, 'location': {}, 'population': 0},
    'windsor': {'full': 'Windsor', 'adjacent-neighbors': {}, 'nearest_neighbors': {'lowry-field', 'washington-virginia-vale'}, 'location': {}, 'population': 0}
}

# Human-readable crime names.
crime_name_lookup = {
    'traffic-accident-dui-duid': {'full':'DUI', 'value': 1 },
    'traffic-accident-hit-and-run': {'full':'Hit and Run', 'value': 1 },
    'burg': {'full':'Burglary', 'value': 1 },
    'sexual-assault': {'full':'Sexual Assault', 'value': 1 },
    'assault': {'full':'Assault', 'value': 1 },
    'robbery': {'full':'Robbery', 'value': 1 },
    'homicide': {'full':'Homicide', 'value': 1 },
    'rape': {'full':'Rape', 'value': 1 },
    'violent': {'full':'Violent crime', 'value': 1 },
    'property': {'full':'Property crime', 'value': 1 },
    'dv': {'full':'Domestic Violence', 'value': 1 },
    'sovereign-treason-viol': {'full':'Treason', 'value': 1 },
    'immigration-violations': {'full':'Immigration violation', 'value': 1 },
    'homicide-family': {'full':'Homicide by a family member', 'value': 1 },
    'hom-willful-kill-non-family-gu': {'full':'Homicide by a stranger w/gun', 'value': 1 },
    'hom-willful-kill-nonfam-wp': {'full':'Homicide by a stranger w/weapon', 'value': 1 },
    'homicide-police-by-gun': {'full':'Homicide of a Police Officer w/gun', 'value': 1 },
    'homicide-police-weapon': {'full':'Homicide of a Police Officer w/weapon', 'value': 1 },
    'homicide-negligent': {'full':'Homicide by negligence', 'value': 1 },
    'hom-wilful-kill-gun': {'full':'Homicide by gun', 'value': 1 },
    'homicide-other': {'full':'Homicide by other means', 'value': 1 },
    'kidnap-minor-to-sex-aslt': {'full':'Kidnap minor to sexually assault', 'value': 1 },
    'kidnap-adult-to-sex-aslt': {'full':'Kidnap adult to sexually assault', 'value': 1 },
    'kidnap-juvenile-victim': {'full':'Kidnap a minor', 'value': 1 },
    'kidnap-adult-victim': {'full':'Kidnap an adult', 'value': 1 },
    'kidnap-dv': {'full':'Domestic violence kidnapping', 'value': 1 },
    'kidnap-abduct-no-ransom-aslt': {'full':'Abduction without ransom or assault', 'value': 1 },
    'kidnap-hijack-aircraft': {'full':'Hijack an aircraft', 'value': 1 },
    'kidnap-parental': {'full':'Kidnapping by parent', 'value': 1 },
    'kidnap-minor-nonparental': {'full':'Kidnapping of a minor by non-parent', 'value': 1 },
    'false-imprisonment': {'full':'False Imprisonment', 'value': 1 },
    'sex-aslt-gun': {'full':'Rape, perpetrator had a gun', 'value': 1 },
    'sex-aslt-rape': {'full':'Rape', 'value': 1 },
    'sex-aslt-rape-pot': {'full':'Rape by a person in a position of trust', 'value': 1 },
    'sex-aslt-strong-arm': {'full':'Rape using the threat of violence', 'value': 1 },
    'sex-aslt-non-rape': {'full':'Unlawful sexual contact', 'value': 1 },
    'sex-aslt-non-rape-pot': {'full':'Unlawful sexual contact', 'value': 1 },
    'sex-asslt-sodomy-boy-strng-arm': {'full':'Sodomy of a male juvenile using bodily force', 'value': 1 },
    'sex-asslt-sodomy-man-strng-arm': {'full':'Sodomy of an adult male using bodily force', 'value': 1 },
    'sex-asslt-sodomy-girl-strg-arm': {'full':'Sodomy of a female juvenile using bodily force', 'value': 1 },
    'sex-asslt-sodomy-woman-str-arm': {'full':'Sodomy of an adult female using bodily force', 'value': 1 },
    'sex-aslt-statutory-rape': {'full':'Statutory rape', 'value': 1 },
    'sex-aslt-statutory-rape-pot': {'full':'Statutory rape by a person in a position of trust', 'value': 1 },
    'sex-aslt-w-object': {'full':'Sexual assault with an object', 'value': 1 },
    'sex-aslt-w-object-pot': {'full':'Sexual assault w/object by a person in a position of trust', 'value': 1 },
    'robbery-business-gun': {'full':'Robbery of a business using a gun', 'value': 1 },
    'robbery-business': {'full':'Robbery of a business using a weapon', 'value': 1 },
    'robbery-busn-strong-arm': {'full':'Robbery of a business using bodily force', 'value': 1 },
    'robbery-street-gun': {'full':'Robbery of a person in the open using a gun', 'value': 1 },
    'robbery-street': {'full':'Robbery of a person in the open', 'value': 1 },
    'robbery-street-strong-arm': {'full':'Robbery of a person in the open using bodily force', 'value': 1 },
    'robbery-residence-gun': {'full':'Robbery of a person in a residence using a gun', 'value': 1 },
    'robbery-residence': {'full':'Robbery of a person in a residence', 'value': 1 },
    'robbery-resd-strong-arm': {'full':'Robbery of a person in a residence using bodily force', 'value': 1 },
    'robbery-purse-snatch-w-force': {'full':'Forcible Purse Snatching', 'value': 1 },
    'robbery-bank': {'full':'Bank Robbery', 'value': 1 },
    'robbery-car-jacking': {'full':'Carjacking - armed', 'value': 1 },
    'robbery-other': {'full':'Robbery - remarks', 'value': 1 },
    'aslt-agg-family-gun': {'full':'Assault causing serious bodily injury by a family member using a gun', 'value': 1 },
    'aslt-agg-family-weapon': {'full':'Assault causing serious bodily injury by a family member using a weapon', 'value': 1 },
    'agg-aslt-strong-arm-dv': {'full':'Assault causing serious bodily injury using bodily force - domestic violence', 'value': 1 },
    'aslt-agg-non-family-gun': {'full':'Assault causing serious bodily injury by a stranger using a gun', 'value': 1 },
    'aslt-agg-non-family-weapon': {'full':'Assault causing serious bodily injury by a stranger using a weapon', 'value': 1 },
    'agg-aslt-strong-arm-nonfam': {'full':'Assault causing serious bodily injury by a stranger using bodily force', 'value': 1 },
    'aslt-agg-police-gun': {'full':'Assault causing serious bodily injury of a police officer using a gun', 'value': 1 },
    'agg-aslt-police-weapon': {'full':'Assault causing serious bodily injury of a police officer using a weapon', 'value': 1 },
    'agg-aslt-police-ofc-stng-arm': {'full':'Assault causing serious bodily injury of a police officer using bodily force', 'value': 1 },
    'assault-simple': {'full':'Assault causing minor bodily injury', 'value': 1 },
    'assault-state': {'full':'Assault causing minor bodily injury', 'value': 1 },
    'assault-dv': {'full':'Assault causing minor bodily injury - domestic violence', 'value': 1 },
    'assault-police-simple': {'full':'Assault causing minor bodily injury to a police officer', 'value': 1 },
    'agg-aslt-gun-other': {'full':'Assault causing serious bodily injury using a gun', 'value': 1 },
    'weapon-fire-into-occ-veh': {'full':'Weapon fired into an occupied vehicle', 'value': 1 },
    'weapon-fire-into-occ-bldg': {'full':'Weapon fired into an occupied building', 'value': 1 },
    'aggravated-assault': {'full':'Assault causing serious bodily injury', 'value': 1 },
    'aggravated-assault-dv': {'full':'Assault causing serious bodily injury - domestic violence', 'value': 1 },
    'menacing-felony-w-weap': {'full':'Threatening to imminently injure with a weapon', 'value': 1 },
    'weapon-flourishing': {'full':'Flourishing a weapon at another person', 'value': 1 },
    'threats-to-injure': {'full':'Threatening to injure', 'value': 1 },
    'harassment-stalking-dv': {'full':'Harassment by stalking - domestic violence', 'value': 1 },
    'threats-city': {'full':'Threatening to injure', 'value': 1 },
    'arson-business': {'full':'Arson of a business', 'value': 1 },
    'arson-residence': {'full':'Arson of a residence', 'value': 1 },
    'arson-other': {'full':'Arson', 'value': 1 },
    'arson-public-building': {'full':'Arson to a public building', 'value': 1 },
    'arson-vehicle': {'full':'Arson of a vehicle', 'value': 1 },
    'extort-threat-inj-person': {'full':'Extort-threaten to injure a person', 'value': 1 },
    'extortion': {'full':'Extortion - other', 'value': 1 },
    'burglary-safe': {'full':'Burglary of a safe', 'value': 1 },
    'burglary-residence': {'full':'Burglary of a residence', 'extra': 1 },
    'burglary-residence-by-force': {'full':'Burglary of a residence with forced entry', 'value': 1 },
    'burg-auto-theft-resd-w-force': {'full':'Burglary and auto theft at a residence with forced entry', 'value': 1 },
    'burglary-business': {'full':'Burglary of a business', 'extra': 1 },
    'burglary-business-by-force': {'full':'Burglary of a business with forced entry', 'value': 1 },
    'burg-auto-theft-busn-w-force': {'full':'Burglary and auto theft at a business with forced entry', 'value': 1 },
    'burglary-residence-no-force': {'full':'Burglary of a residence without forced entry', 'value': 1 },
    'burg-auto-theft-resd-no-force': {'full':'Burglary and auto theft at a residence without forced entry', 'value': 1 },
    'burglary-business-no-force': {'full':'Burglary of a business without forced entry', 'value': 1 },
    'burg-auto-theft-busn-no-force': {'full':'Burglary and auto theft at a business without forced entry', 'value': 1 },
    'burglary-poss-of-tools': {'full':'Possession of burglary tools', 'value': 1 },
    'burglary-other': {'full':'Burglary - other', 'value': 1 },
    'by-force': {'full':'Burglary: Forced Entry', 'extra': 1 },
    'no-force': {'full':'Burglary: Unforced Entry', 'extra': 1 },
    'theft-pick-pocket': {'full':'Pocketpicking', 'value': 1 },
    'theft-purse-snatch-no-force': {'full':'Purse snatching without force', 'value': 1 },
    'theft-shoplift': {'full':'Shoplifting', 'value': 1 },
    'theft-parts-from-vehicle': {'full':'Theft of parts from a vehicle', 'value': 1 },
    'theft-items-from-vehicle': {'full':'Theft of items from a vehicle', 'value': 1 },
    'burglary-vending-machine': {'full':'Theft from a vending machine', 'value': 1 },
    'theft-from-bldg': {'full':'Theft from a building', 'value': 1 },
    'theft-from-yards': {'full':'Theft from a yard', 'value': 1 },
    'theft-from-mails': {'full':'Theft from a mailbox', 'value': 1 },
    'larc-from-bank-type-inst': {'full':'Theft from a bank', 'value': 1 },
    'theft-other': {'full':'Theft - other', 'value': 1 },
    'theft-bicycle': {'full':'Bicycle theft', 'value': 1 },
    'theft-gas-drive-off': {'full':'Theft of fuel by driving off without paying', 'value': 1 },
    'theft-of-cable-services': {'full':'Theft of cable services', 'value': 1 },
    'theft-stln-veh-const-eqpt': {'full':'Theft of construction equipment', 'value': 1 },
    'theft-stln-vehicle-trailer': {'full':'Theft of a trailer', 'value': 1 },
    'theft-vehicle-strip': {'full':'Vehicle stolen and stripped', 'value': 1 },
    'theft-of-motor-vehicle': {'full':'Motor vehicle theft', 'value': 1 },
    'theft-motor-veh-joy-ride': {'full':'Unauthorized use of a vehicle or joy ride', 'value': 1 },
    'forgery-checks': {'full':'Forgery of checks', 'value': 1 },
    'forgery-counterfeit-of-obj': {'full':'Counterfeiting an object', 'value': 1 },
    'altering-vin-number': {'full':'Altering a vehicle VIN number', 'value': 1 },
    'forgery-pass-forged-obj': {'full':'Passing forged documents', 'value': 1 },
    'forg-pass-counterfeit-obj': {'full':'Passing counterfeited objects (tickets, bonds, etc)', 'value': 1 },
    'forgery-poss-of-forged-inst': {'full':'Possession of a forged instrument', 'value': 1 },
    'forgery-poss-of-forged-ftd': {'full':'Possession of a forged financial transaction device (credit & debit cards)', 'value': 1 },
    'forg-poss-counterfeit-obj': {'full':'Possession of counterfeited objects (tickets, bonds, etc)', 'value': 1 },
    'forgery-posses-forge-device': {'full':'Possession of counterfeiting device', 'value': 1 },
    'forgery-other': {'full':'Forgery - other', 'value': 1 },
    'drug-forgery-to-obtain': {'full':'Forgery to obtain drugs', 'value': 1 },
    'theft-confidence-game': {'full':'Theft by confidence game', 'value': 1 },
    'theft-of-rental-property': {'full':'Theft of rental property', 'value': 1 },
    'theft-fail-return-rent-veh': {'full':'Failure to return rental vehicle', 'value': 1 },
    'fraud-identity-theft': {'full':'Identity theft', 'value': 1 },
    'fraud-criminal-impersonation': {'full':'Criminal impersonation', 'value': 1 },
    'fraud-gather-id-info-deception': {'full':'Gathering personal information by deception', 'value': 1 },
    'fraud-possess-id-theft-tools': {'full':'Possession of identity theft tools', 'value': 1 },
    'impersonation-of-police': {'full':'Police impersonation', 'value': 1 },
    'theft-unauth-use-of-ftd': {'full':'Unauthorized use of a financial transaction device', 'value': 1 },
    'fraud-unauthorized-use-of-ftd': {'full':'Unauthorized use of a financial transaction device', 'value': 1 },
    'fraud-nsf-closed-account': {'full':'Fraud by check due to insufficient funds', 'value': 1 },
    'fraud-by-telephone': {'full':'Fraud by telephone', 'value': 1 },
    'fraud-by-wire': {'full':'Fraud by wire', 'value': 1 },
    'fraud-by-use-of-computer': {'full':'Fraud by use of computer', 'value': 1 },
    'fraud-other': {'full':'Fraud - other', 'value': 1 },
    'failure-to-pay-cab-fare': {'full':'Failure to pay cab, bus or rail fare', 'value': 1 },
    'theft-of-meals': {'full':'Theft of meals', 'value': 1 },
    'theft-of-services': {'full':'Theft of services', 'value': 1 },
    'drug-fraud-to-obtain': {'full':'Fraud to obtain drugs', 'value': 1 },
    'pawn-broker-viol': {'full':'Pawn broker violation', 'value': 1 },
    'embezzle-bus-property': {'full':'Embezzlement of business property', 'value': 1 },
    'theft-embezzle': {'full':'Embezzlement by an employee', 'value': 1 },
    'stolen-property-sale-of': {'full':'Sale of stolen property', 'value': 1 },
    'stolen-property-buy-sell-rec': {'full':'Buy, sell or receive stolen property', 'value': 1 },
    'outside-steal-recovered-veh': {'full':'Recovered vehicle stolen outside Denver', 'value': 1 },
    'stolen-property-possession': {'full':'Possession of stolen property', 'value': 1 },
    'fraud-possess-financial-device': {'full':'Possession of a financial device', 'value': 1 },
    'damaged-prop-bus': {'full':'Damaged business property', 'value': 1 },
    'criminal-mischief-private': {'full':'Criminal mischief to private property', 'value': 1 },
    'criminal-mischief-public': {'full':'Criminal mischief to public property', 'value': 1 },
    'criminal-mischief-other': {'full':'Criminal mischief - other', 'value': 1 },
    'criminal-mischief-mtr-veh': {'full':'Criminal mischief to a motor vehicle', 'value': 1 },
    'criminal-mischief-graffiti': {'full':'Criminal mischief - graffiti', 'value': 1 },
    'drug-hallucinogen-mfr': {'full':'Manufacture of a hallucinogenic drug', 'value': 1 },
    'drug-hallucinogen-sell': {'full':'Selling a hallucinogenic drug', 'value': 1 },
    'drug-hallucinogen-possess': {'full':'Possession of a hallucinogenic drug', 'value': 1 },
    'drug-heroin-sell': {'full':'Selling heroin', 'value': 1 },
    'drug-heroin-possess': {'full':'Possession of heroin', 'value': 1 },
    'drug-opium-or-deriv-sell': {'full':'Selling opium or an opium derivative', 'value': 1 },
    'drug-opium-or-deriv-possess': {'full':'Possession of opium or an opium derivative', 'value': 1 },
    'drug-cocaine-sell': {'full':'Selling cocaine', 'value': 1 },
    'drug-cocaine-possess': {'full':'Possession of cocaine', 'value': 1 },
    'drug-synth-narcotic-sell': {'full':'Selling a synthetic narcotic drug', 'value': 1 },
    'drug-synth-narcotic-possess': {'full':'Possession of a synthetic narcotic drug', 'value': 1 },
    'drug-poss-paraphernalia': {'full':'Possession of drug paraphernalia', 'value': 1 },
    'drug-marijuana-sell': {'full':'Selling marijuana', 'value': 1 },
    'drug-marijuana-possess': {'full':'Possession of marijuana', 'value': 1 },
    'drug-marijuana-cultivation': {'full':'Cultivation of marijuana', 'value': 1 },
    'drug-methamphetamine-mfr': {'full':'Manufacture of methampetamine', 'value': 1 },
    'drug-methampetamine-sell': {'full':'Selling methampetamine', 'value': 1 },
    'drug-methampetamine-possess': {'full':'Possession of methampetamine', 'value': 1 },
    'drug-barbiturate-mfr': {'full':'Manufacture of a barbiturate', 'value': 1 },
    'drug-barbiturate-sell': {'full':'Selling a barbiturate', 'value': 1 },
    'drug-barbiturate-possess': {'full':'Possession of a barbiturate', 'value': 1 },
    'drug-pcs-other-drug': {'full':'Other dangerous drugs - PCS', 'value': 1 },
    'drug-make-sell-other-drug': {'full':'Manufacture or sell other dangerous drugs', 'value': 1 },
    'sex-aslt-fondle-adult-victim': {'full':'Fondling of an adult', 'value': 1 },
    'indecent-exposure': {'full':'Indecent exposure', 'value': 1 },
    'sex-off-incest-with-adult': {'full':'Incest with an adult', 'value': 1 },
    'window-peeping': {'full':'Window Peeping', 'value': 1 },
    'sex-off-fail-to-register': {'full':'Failure to register as a sex offender', 'value': 1 },
    'sex-off-registration-viol': {'full':'Sex offender registration violation', 'value': 1 },
    'indecent-exposure-to-adult': {'full':'Indecent exposure to an adult', 'value': 1 },
    'sex-off-other': {'full':'Sex offense - other', 'value': 1 },
    'obscene-material-possess': {'full':'Possession of obscene material', 'value': 1 },
    'obscene-material-mfr': {'full':'Manufacture of obscene material', 'value': 1 },
    'other-obscenity-crime': {'full':'Other obscenity crime', 'value': 1 },
    'bigamy': {'full':'Bigamy', 'value': 1 },
    'gambling-card-game-operating': {'full':'Operating a gambling card game', 'value': 1 },
    'gambling-dice-game-operating': {'full':'Operating a gambling dice game', 'value': 1 },
    'gambling-possess-gamb-device': {'full':'Possession of a gambling device', 'value': 1 },
    'gambling-device': {'full':'Running a gambling operation', 'value': 1 },
    'gambling-lottery-operating': {'full':'Running an illegal lottery', 'value': 1 },
    'gambling-sports-tampering': {'full':'Tampering with sports', 'value': 1 },
    'gambling-betting-wagering': {'full':'Gambling - betting or wagering', 'value': 1 },
    'gambling-gaming-operation': {'full':'Gambling - gaming operation', 'value': 1 },
    'gambling-illegal': {'full':'Illegal gambling', 'value': 1 },
    'prostitution-keep-a-house-of': {'full':'Keeping a house of prostitution', 'value': 1 },
    'prostitution-procure-for': {'full':'Procure for prostitution (trafficking operating a bordelo)', 'value': 1 },
    'prostitution-pimping': {'full':'Pimping for prostitution', 'value': 1 },
    'prostitution-engaging-in': {'full':'Engaging in prostitution', 'value': 1 },
    'prostitution': {'full':'Prostitution', 'value': 1 },
    'prostitution-aiding': {'full':'Aiding the act of prostitution', 'value': 1 },
    'prostituion-display-for': {'full':'Display for prostitution', 'value': 1 },
    'liquor-manufacturing': {'full':'Manufacture of liquor', 'value': 1 },
    'liquor-sell': {'full':'Illegal sale of liquor', 'value': 1 },
    'liquor-possession': {'full':'Illegal possession of liquor', 'value': 1 },
    'liquor-misrepresent-age-minor': {'full':'Liquor law violation', 'value': 1 },
    'liquor-other-viol': {'full':'Liquor law violation - other', 'value': 1 },
    'public-intoxication': {'full':'Public intoxication', 'value': 1 },
    'police-resisting-arrest': {'full':'Resisting arrest', 'value': 1 },
    'police-obstruct-investigation': {'full':'Obstruction of a criminal investigation', 'value': 1 },
    'police-false-information': {'full':'Giving false information to police', 'value': 1 },
    'police-making-a-false-rpt': {'full':'Making a false report to police', 'value': 1 },
    'police-refusing-aid-to': {'full':'Refusing to aid an officer', 'value': 1 },
    'failure-to-report-abuse': {'full':'Failure to report abuse', 'value': 1 },
    'police-disobey-lawful-order': {'full':'Failure to obey a lawful order by police', 'value': 1 },
    'police-interference': {'full':'Obstructing police', 'value': 1 },
    'escape': {'full':'Escape of a prisoner', 'value': 1 },
    'escape-aiding': {'full':'Aiding the escape of a prisoner', 'value': 1 },
    'escape-other': {'full':'Escape or flight', 'value': 1 },
    'intimidation-of-a-witness': {'full':'Intimidation of a witness', 'value': 1 },
    'obstruct-jud-court-order-vio': {'full':'Obstructing a court order', 'value': 1 },
    'parole-violation': {'full':'Parole violation', 'value': 1 },
    'probation-violation': {'full':'Probation violation', 'value': 1 },
    'failure-to-appear': {'full':'Failure to appear', 'value': 1 },
    'violation-of-restraining-order': {'full':'Violation of a restraining order', 'value': 1 },
    'violation-of-court-order': {'full':'Violation of a court order', 'value': 1 },
    'violation-of-custody-order': {'full':'Violation of a court order', 'value': 1 },
    'obstructing-govt-operation': {'full':'Obstruction of a government operation', 'value': 1 },
    'bribery': {'full':'Bribery', 'value': 1 },
    'weapon-altering-serial-number': {'full':'Altering the serial number', 'value': 1 },
    'weapon-carrying-concealed': {'full':'Carrying a concealed weapon', 'value': 1 },
    'weapon-carrying-prohibited': {'full':'Carrying a prohibited weapon', 'value': 1 },
    'explosive-incendiary-dev-use': {'full':'Using an explosive/incendiary device', 'value': 1 },
    'explosives-posses': {'full':'Possession of an explosive', 'value': 1 },
    'explosive-incendiary-dev-pos': {'full':'Possession of an explosive/incendiary device', 'value': 1 },
    'weapon-poss-illegal-dangerous': {'full':'Possession of an illegal/dangerous weapon', 'value': 1 },
    'weapon-by-prev-offender-powpo': {'full':'Possession of a weapon - POWPO', 'value': 1 },
    'weapon-unlawful-discharge-of': {'full':'Unlawful discharge of a weapon', 'value': 1 },
    'weapon-flourishing': {'full':'Flourishing of a weapon', 'value': 1 },
    'weapon-unlawful-sale': {'full':'Unlawful sale of a weapon', 'value': 1 },
    'bomb-threat': {'full':'Bomb threat', 'value': 1 },
    'weapon-other-viol': {'full':'Weapon - other', 'value': 1 },
    'riot-incite': {'full':'Inciting a riot', 'value': 1 },
    'riot': {'full':'Engaging in a riot', 'value': 1 },
    'police-interference': {'full':'Police Interference', 'value': 1 },
    'riot-unlawful-assembly': {'full':'Unlawful assembly', 'value': 1 },
    'harassment': {'full':'Harassment', 'value': 1 },
    'harassment-dv': {'full':'Harassment - DV', 'value': 1 },
    'harassment-obscene': {'full':'Obscene harassment', 'value': 1 },
    'harassment-sexual-in-nature': {'full':'Harassment - sexual in nature', 'value': 1 },
    'pub-peace-desecrate-symb': {'full':'Desecrating the flag', 'value': 1 },
    'public-fighting': {'full':'Public fighting', 'value': 1 },
    'disturbing-the-peace': {'full':'Disturbing the peace', 'value': 1 },
    'curfew': {'full':'Curfew', 'value': 1 },
    'loitering': {'full':'Loitering', 'value': 1 },
    'public-peace-vagrancy': {'full':'Vagrancy', 'value': 1 },
    'public-peace-other': {'full':'Public peace - other', 'value': 1 },
    #'traf-habitual-offender': {'full':'Habitual traffic offender', 'value': 1 },
    'traf-vehicular-homicide': {'full':'Vehicular homicide', 'value': 1 },
    #'traf-impound-vehicle': {'full':'Impound abandoned vehicle on right-of-way', 'value': 1 },
    'traf-vehicular-assault': {'full':'Vehicular assault', 'value': 1 },
    #'traf-other': {'full':'Traffic offense - other', 'value': 1 },
    'vehicular-eluding': {'full':'Vehicular eluding', 'value': 1 },
    'vehicular-eluding-no-chase': {'full':'Vehicular eluding - no chase', 'value': 1 },
    'health-violations': {'full':'Health & safety violations', 'value': 1 },
    'eavesdropping': {'full':'Eavesdropping', 'value': 1 },
    'criminal-trespassing': {'full':'Criminal trespassing', 'value': 1 },
    'wiretapping': {'full':'Wiretapping', 'value': 1 },
    'contraband-possession': {'full':'Possession of contraband', 'value': 1 },
    'contraband-into-prison': {'full':'Smuggle contraband to prisoner', 'value': 1 },
    'election-law-violation': {'full':'Election laws violation', 'value': 1 },
    'money-laundering': {'full':'Money laundering', 'value': 1 },
    'tax-violations': {'full':'Tax revenue violation', 'value': 1 },
    'animal-cruelty-to': {'full':'Cruelty to animals', 'value': 1 },
    'illegal-dumping': {'full':'Illegal dumping', 'value': 1 },
    'other-conservation-crime': {'full':'Other conversation offense', 'value': 1 },
    'littering': {'full':'Littering', 'value': 1 },
    'other-enviornment-animal-viol': {'full':'Other environmental or animal offense', 'value': 1 },
    'animal-poss-of-dangerous': {'full':'Possession of a dangerous animal', 'value': 1 },
    'money-laundering': {'full':'Money laundering', 'value': 1 },
    'crimes-against-person-other': {'full':'Crimes against a person - other', 'value': 1 },
    'homicide-solicitation': {'full':'Solicitation to commit homicide', 'value': 1 },
    'reckless-endangerment': {'full':'Reckless endangerment', 'value': 1 },
    'disarming-a-peace-officer': {'full':'Disarming a peace officer', 'value': 1 },
    'homicide-accessory-to': {'full':'Accessory to commit homicide', 'value': 1 },
    'property-crimes-other': {'full':'Property crimes - other', 'value': 1 },
    'property-crimes-other': {'full':'Property crimes - other', 'value': 1 },
    'morals-other-moral-off': {'full':'Morals / decency offense - other', 'value': 1 },
    'public-order-crimes-other': {'full':'Public order offense - other', 'value': 1 },
    'fireworks-possession': {'full':'Possession of fireworks', 'value': 1 },
    'public-order-crimes-other': {'full':'Public order offense - other', 'value': 1 },
    'accessory-conspiracy-to-crime': {'full':'Accessory / conspiracy to crime', 'value': 1 }
}

# Here so we can reference URLS such as http://denvercrimes.com/caphill 
# and redirect requests to an actual page.
neighborhood_shortcut_lookup = {
    'athmar-park': 'athmar-park',
    'auraria': 'auraria',
    'baker': 'baker',
    'barnum': 'barnum',
    'barnum-west': 'barnum-west',
    'bear-valley': 'bear-valley',
    'belcaro': 'belcaro',
    'berkeley': 'berkeley',
    'caphill': 'capitol-hill',
    'cbd': 'cbd',
    'chaffee-park': 'chaffee-park',
    'cheesman-park': 'cheesman-park',
    'cherry-creek': 'cherry-creek',
    'city-park': 'city-park',
    'city-park-west': 'city-park-west',
    'civic-center': 'civic-center',
    'clayton': 'clayton',
    'cole': 'cole',
    'college-view-south-platte': 'college-view-south-platte',
    'congress-park': 'congress-park',
    'cory-merrill': 'cory-merrill',
    'dia': 'dia',
    'east-colfax': 'east-colfax',
    'elyria-swansea': 'elyria-swansea',
    'five-points': 'five-points',
    'gateway-green-valley-ranch': 'gateway-green-valley-ranch',
    'globeville': 'globeville',
    'goldsmith': 'goldsmith',
    'hale': 'hale',
    'hampden': 'hampden',
    'hampden-south': 'hampden-south',
    'harvey-park': 'harvey-park',
    'harvey-park-south': 'harvey-park-south',
    'highland': 'highland',
    'hilltop': 'hilltop',
    'indian-creek': 'indian-creek',
    'jefferson-park': 'jefferson-park',
    'kennedy': 'kennedy',
    'lincoln-park': 'lincoln-park',
    'lowry-field': 'lowry-field',
    'mar-lee': 'mar-lee',
    'marston': 'marston',
    'montbello': 'montbello',
    'montclair': 'montclair',
    'north-capitol-hill': 'north-capitol-hill',
    'northeast-park-hill': 'northeast-park-hill',
    'north-park-hill': 'north-park-hill',
    'overland': 'overland',
    'platt-park': 'platt-park',
    'regis': 'regis',
    'ruby-hill': 'ruby-hill',
    'skyland': 'skyland',
    'sloan-lake': 'sloan-lake',
    'southmoor-park': 'southmoor-park',
    'south-park-hill': 'south-park-hill',
    'speer': 'speer',
    'stapleton': 'stapleton',
    'sunnyside': 'sunnyside',
    'sun-valley': 'sun-valley',
    'union-station': 'union-station',
    'university-hills': 'university-hills',
    'university-park': 'university-park',
    'university': 'university',
    'valverde': 'valverde',
    'villa-park': 'villa-park',
    'virginia-village': 'virginia-village',
    'washington-park-west': 'washington-park-west',
    'washington-virginia-vale': 'washington-virginia-vale',
    'wellshire': 'wellshire',
    'west-colfax': 'west-colfax',
    'west-highland': 'west-highland',
    'westwood': 'westwood',
    'whittier': 'whittier',
    'windsor': 'windsor'
}
crime_types = ['criminal-mischief-mtr-veh', 'burglary-residence-no-force', 'vehicular-eluding-no-chase', 'traf-other', 'aslt-agg-police-gun', 'weapon-unlawful-discharge-of', 'theft-other', 'forgery-other', 'drug-barbiturate-possess', 'robbery-car-jacking', 'forgery-poss-of-forged-inst', 'failure-to-appear', 'theft-stln-veh-const-eqpt', 'arson-vehicle', 'liquor-possession', 'robbery-bank', 'other-enviornment-animal-viol', 'sex-aslt-non-rape', 'police-false-information', 'pawn-broker-viol', 'drug-methampetamine-possess', 'criminal-mischief-graffiti', 'burglary-business-by-force', 'weapon-carrying-concealed', 'harassment-dv', 'forgery-counterfeit-of-obj', 'drug-opium-or-deriv-sell', 'aggravated-assault', 'drug-cocaine-possess', 'robbery-street', 'theft-unauth-use-of-ftd', 'sex-off-fail-to-register', 'weapon-other-viol', 'violation-of-custody-order', 'theft-parts-from-vehicle', 'window-peeping', 'escape', 'violation-of-court-order', 'harassment', 'drug-fraud-to-obtain', 'criminal-mischief-other', 'theft-pick-pocket', 'bomb-threat', 'drug-hallucinogen-sell', 'aggravated-assault-dv', 'burglary-safe', 'arson-other', 'drug-poss-paraphernalia', 'theft-fail-return-rent-veh', 'theft-gas-drive-off', 'weapon-carrying-prohibited', 'weapon-by-prev-offender-powpo', 'theft-from-bldg', 'criminal-trespassing', 'liquor-misrepresent-age-minor', 'police-disobey-lawful-order', 'fraud-by-use-of-computer', 'burg-auto-theft-resd-w-force', 'drug-pcs-other-drug', 'drug-methampetamine-sell', 'burg-auto-theft-busn-w-force', 'impersonation-of-police', 'drug-marijuana-possess', 'theft-shoplift', 'assault-dv', 'fraud-identity-theft', 'theft-purse-snatch-no-force', 'drug-forgery-to-obtain', 'kidnap-dv', 'false-imprisonment', 'illegal-dumping', 'disturbing-the-peace', 'burg-auto-theft-resd-no-force', 'obstructing-govt-operation', 'public-fighting', 'police-making-a-false-rpt', 'weapon-poss-illegal-dangerous', 'indecent-exposure', 'harassment-sexual-in-nature', 'threats-to-injure', 'fireworks-possession', 'vehicular-eluding', 'drug-methamphetamine-mfr', 'weapon-fire-into-occ-veh', 'homicide-other', 'drug-hallucinogen-possess', 'violation-of-restraining-order', 'property-crimes-other', 'menacing-felony-w-weap', 'traf-vehicular-assault', 'theft-items-from-vehicle', 'theft-from-mails', 'sex-aslt-fondle-adult-victim', 'fraud-by-telephone', 'theft-of-motor-vehicle', 'stolen-property-buy-sell-rec', 'agg-aslt-police-weapon', 'robbery-purse-snatch-w-force', 'burg-auto-theft-busn-no-force', 'assault-police-simple', 'fraud-nsf-closed-account', 'theft-of-services', 'drug-heroin-sell', 'burglary-poss-of-tools', 'weapon-fire-into-occ-bldg', 'sex-aslt-rape', 'forgery-checks', 'fraud-criminal-impersonation', 'public-order-crimes-other', 'prostitution-engaging-in', 'burglary-residence-by-force', 'assault-simple', 'drug-cocaine-sell', 'theft-bicycle', 'animal-cruelty-to', 'arson-residence', 'traf-habitual-offender', 'drug-synth-narcotic-possess', 'police-resisting-arrest', 'kidnap-adult-victim', 'drug-make-sell-other-drug', 'burglary-vending-machine', 'police-obstruct-investigation', 'weapon-flourishing', 'drug-marijuana-sell', 'intimidation-of-a-witness', 'extortion', 'harassment-stalking-dv', 'robbery-business', 'burglary-business-no-force', 'contraband-into-prison', 'contraband-possession', 'traf-impound-vehicle', 'drug-heroin-possess', 'police-interference', 'theft-embezzle', 'explosive-incendiary-dev-pos', 'robbery-residence', 'theft-stln-vehicle-trailer']
keys = ['INCIDENT_ID','OFFENSE_ID','OFFENSE_CODE','OFFENSE_CODE_EXTENSION','OFFENSE_TYPE_ID','OFFENSE_CATEGORY_ID','FIRST_OCCURRENCE_DATE','LAST_OCCURRENCE_DATE','REPORTED_DATE','INCIDENT_ADDRESS','GEO_X','GEO_Y','GEO_LON','GEO_LAT','DISTRICT_ID','PRECINCT_ID','NEIGHBORHOOD_ID']
neighborhoods = ['wellshire', 'bear-valley', 'hilltop', 'cbd', 'university-hills', 'overland', 'speer', 'union-station', 'washington-virginia-vale', 'marston', 'north-capitol-hill', 'city-park', 'sloan-lake', 'five-points', 'sun-valley', 'westwood', 'cole', 'windsor', 'platt-park', 'jefferson-park', 'harvey-park', 'skyland', 'sunnyside', 'southmoor-park', 'ruby-hill', 'capitol-hill', 'barnum-west', 'harvey-park-south', 'dia', 'athmar-park', 'elyria-swansea', 'lowry-field', 'goldsmith', 'stapleton', 'chaffee-park', 'berkeley', 'washington-park', 'indian-creek', 'barnum', 'montbello', 'civic-center', 'hampden-south', 'globeville', 'city-park-west', 'clayton', 'northeast-park-hill', 'country-club', 'hale', 'mar-lee', 'lincoln-park', 'gateway-green-valley-ranch', 'west-highland', 'congress-park', 'regis', 'east-colfax', 'whittier', 'belcaro', 'hampden', 'fort-logan', 'college-view-south-platte', 'montclair', 'baker', 'kennedy', 'cherry-creek', 'cheesman-park', 'west-colfax', 'south-park-hill', 'cory-merrill', 'rosedale', 'valverde', 'university-park', 'auraria', 'north-park-hill', 'highland', 'villa-park', 'university', 'virginia-village', 'washington-park-west']
populations = {'wellshire': '3133', 'cbd': '3648', 'university-hills': '5327', 'overland': '2218', 'speer': '10954', 'gateway-green-valley-ranch': '29201', 'ruby-hill': '9820', 'marston': '11132', 'north-capitol-hill': '5823', 'city-park': '2907', 'indian-creek': '3096', 'five-points': '12712', 'sun-valley': '1448', 'westwood': '15486', 'cole': '4651', 'washington-park-west': '6393', 'platt-park': '5393', 'harvey-park-south': '8393', 'villa-park': '8758', 'athmar-park': '8898', 'skyland': '3106', 'north-park-hill': '9382', 'sunnyside': '9726', 'southmoor-park': '3826', 'jefferson-park': '2552', 'capitol-hill': '14708', 'windsor': '12589', 'barnum-west': '5376', 'virginia-village': '12844', 'montbello': '30348', 'bear-valley': '8889', 'goldsmith': '5808', 'stapleton': '13948', 'chaffee-park': '3874', 'cory-merrill': '3892', 'northeast-park-hill': '7822', 'union-station': '4348', 'washington-park': '6905', 'barnum': '6111', 'elyria-swansea': '6401', 'civic-center': '1577', 'hampden-south': '14370', 'globeville': '3687', 'city-park-west': '4844', 'clayton': '4336', 'cheesman-park': '7971', 'country-club': '3001', 'hale': '6936', 'mar-lee': '12452', 'lincoln-park': '6119', 'berkeley': '8112', 'west-highland': '8540', 'harvey-park': '11525', 'regis': '3934', 'east-colfax': '10191', 'whittier': '4831', 'belcaro': '4172', 'hampden': '17547', 'fort-logan': '8532', 'college-view-south-platte': '6498', 'west-colfax': '9740', 'baker': '4879', 'kennedy': '4464', 'cherry-creek': '5589', 'dia': '1165', 'congress-park': '10235', 'south-park-hill': '8590', 'rosedale': '2553', 'valverde': '3941', 'lowry-field': '8067', 'washington-virginia-vale': '13030', 'auraria': '705', 'hilltop': '8190', 'highland': '8429', 'montclair': '5456', 'university': '9375', 'university-park': '7491', 'sloan-lake': '7238'}

